---
title: "265_typst_examples.qmd"
format:
  typst:
    toc: true
    section-numbering: 1.1.a
    columns: 1
description: 265_typst_example.qmd;   typst  basics + math
---

- This is a quarto (.qmd) file.  - Embeds raw `typst` (ex: math)  and `r` chunks.  
- To render:   quarto render 265_typst_example.qmd
- R chunks, still use knitr, see example below.  
- REF:  good annotated typst examples: https://sitandr.github.io/typst-examples-book/book/basics/tutorial/markup.html
- Use backslash to linebreak 
- typst comments:  use " // or /* multiline */ slash  
- use function #v(10) for vertical space


```{=typst}
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge
```

### Functions
**Functions begin with pound ** \ 
Followed by args (in parenthesis) and content in square brackets
```{=typst}
#lorem(20)
````
***
**More function examples:**
```{=typst}
#list[
  All that markup is just a #emph[syntax sugar] over functions!


#text(size: 0.8em)[This is content]
#text(orange)[orange content], but this is regular content.
#link("https://typst.app/docs/reference/")[link to Official Reference].
]
```



### Block with background color and inset 
```{=typst}

#set align(center)
#block(
  //fill: rgb("f58025"),
  fill: silver,
  inset: 14pt,
  width: 100%,
[Can use typ file, but then use `typst` ecosystem to render]
)
#set align(left)
```

### use a variable
```{=typst}

#let jr = [jim]

The variable 'jr' holds value #jr

#table(
  columns: (1fr, 1fr),
  [variable], [Typst],
  [jr], jr,
)
```

### simple quote block
```{=typst}
#quote(block: true)[
  So #text(red)[_that_] allows me to write
  _literally anything_ in things
  I pass to #underline[functions]!
]
```
### Box + a show function, a trigger, then action: 
```{=typst}
#show emph: set text(blue) // emph renders as blue
#show "typst": set text(orange)
#box(stroke: gray, inset: 1em)[typst should be _taught_]
```



### Simple R   (uses `{r}` and knitr
```{r}
1+2
```

### Linear Algebra

#### with special symbols
```{=typst}
$
forall v, w in V, alpha in KK: alpha dot (v + w) = alpha v + alpha w
$
```

### unicode

$$
∀ v, w ∈ V, α ∈ 𝕂: α ⋅ (v + w) = α v + α w
$$

### SVD

A can be any matrix

```{=typst}
$A = U Sigma V$
Phi

2 + x = ?
```

This renders as PDF.  It uses quarto via its built-in typst cli to render pdf.
REF:   https://quarto.org/docs/output-formats/typst.html

### Diagrams
*Diagram, includes nodes and edges

```{=typst}
#diagram(cell-size: 15mm, $
	G edge(f, ->) edge("d", pi, ->>) & im(f) \
	G slash ker(f) edge("ur", tilde(f), "hook-->")
$)\
```
