
vim:linebreak:spell:nowrap tw=78 fo=tqlnr foldcolumn=3 


<!--
!pandoc % -t latex -V linkcolor:blue -V fontsize=12pt -V geometry:margin=0.5in -o ~/Downloads/print_and_delete/out.pdf

-H header
-V or --variable
--pdf-engine=xelatex


-->
Germany
[failing nytimes.com](www.nytimes.com)

## Russia
- Mongol vs Turkic vs Tatar?
-	populated long ago (~2000-3000 BC?) , possible Scandinavian offshoot?
-	859AD (Kiev) - 1st recorded writing (errors?)
-	Rus' = OLD EAST SLAV
-	1240-1480 AD Mongol invade.
-		-	Adopt Islam.
-		- Convert Tatar (Who, where, when?, from N. Central Asia)

Peter the Great (1689 - 1725) kicks out Swedes, makes St. Peter's capital.
Academy (1724), esp for math, attracts Euler, Bernoulli.

1730 - 1745, turmoil, trials, executions, till Catherine the Great, Euler
returns.
(Berlin Academy - Fred the Great, ego but not so great, after 7 years war: famine)

- Ottoman (when)  depopulate Ukraine, as slaves brought to  Black Sea.
- Gives rise to Cossack's?   When Where?
- ~1852 Russia expansionary; considers itself true defenders of religion; in
Holy Land, Russians considered pious visitors, but French are merely
'tourists'.   Russia eyes Ottman, while Fr & UK, despite own suspicions of
each other, prop up Ottoman to block Russians.

Czar Nicholas I - dies during Crimean War
1877-8 - Russo Turkist War
Source:  Rose Pesotta (HD6509.P47)
1881 - ass'n Alexander II, son Alexander III rules
repression; ends period of limited reform
BUT seed planted during liberalization remains, now underground discussions, travelers, variety of ideas, esp in shetls.   Boys faced constription, but girls if so radicalized faced reality of Jewish culture (babies, domestic work, religion...)
1881 - 1914 1/3 of East Europian Jews go to US.

1892 - Finance Minister **Witte**, studied math (infintesimal numbers); extraordinary ability to organize, to decide, think long term; even diplomacy;  in short:  gets it done.
Also considered ruthless.
As finance minister, also controls RR and sets in motion financing, planning and organization to build **Trans-Siberian**.  (Witte career started with railroad and he kept rising.)
5,750 miles; steppe can freeze, but becomes swamp in spring (trecherous for RR)
late 19th - rising **Russo-Anglo tension** (Afganistan, Pacific) while Japan silently develops.
Russian gov't pays for RR (too unprofitable for private company); Short-cut via NE China; Witte arranges French loans to cover China's indemnity for Sino-Japan War 1994; Witte awarded right to RR in NE China.  establishes Harbin,  Chinese Eastern RR and Southern Manchuian (to Dalian). (Rights to build RR includes things like Russian troops to guard the RR.)
1894 - **Alexander III** dies in 40s, son **Nicholas II** is czar, but not yet prepared.
Nicholas II fires Witte (too much of threat?); 

Trans-Siberan done by 1903-4; enormous project and challenge.  Must
improve Siberan infrasture, labor along the way. Done < 10 years is
amazing.  Poorly done, (can be immproved) but this is understood, mostly on-budget,
on-time. .. goal is to finish.  US benefits: steel, rolling stock,
bridges done in US.  Trans-Siberian is gov't managed and planned
project! (contacts allow to privage companies.) Auto route not done till late 20th.  Trans-Siberian is big
success.

**But, triggers Russo-Japanase War, 1904-5**  Like England, no way Japan will allow another power to play in its waters.  Japan strikes just before trans-Siberian is complete (to limit supplies, troop transports ...)





1760
George III (~ 17) educated, but poor understanding ppl.
Continent (esp France) respect English power, but not English culture, resistance to change, a Parliament that acquiases.   FRANCE is the country with ideas, innovation.

Great Terror - show-trials, Bukharin, Lev Kamenev, Zinoviev,  Alexi Rykov, but Pasternak
(born 1890) asks why spared?     


\section{Ottoman}
-   330  Constantine establishes Eastern outpost.
-   1054 Rome excommunicates East.
-   late 11th  end Crusades; Christians hold HolyLand.
-   1204 Constantinople - sacked by western crusaders; tension between 2
Christianities. 
-   1405 Ottoman seize Constantinople - but very tolerant.  Russia
increasingly orthodox.
-   15-19th Both France and Russia have claims `spiritual` and protector ties
    to Holy land.  Monks, some also not so pious, do all the work in Holy
    Land.
-   1852 SPARK. Unruly pilgrims, not so pious...   Nicholas I extends
protection.  Napolean III (?) seeking support of Fr Catholics also steps in;
French warships to Holy Land.  Now UK is nervous.


## English Civil War
*  Gentry, landed Gentry:  upper class, but not nobles or church, inherited
    land, able to live by collecting rent.  Some actually wealthier  than
    nobles. 
\section{England - 17th}
1649 - Charles I beheaded (impeached)
1684 - James II (Catholic) succeeds brother Charles II.
1689 - William III (from Netherlands) removes James II .  **Glorious
Revolution** was actual neither.   Replaced one king with another - EXCEPT
King no longer sovereign but **constitutional monarch** meaning beholden to
English people(really?) and not elected by GOD.   **Whig** triumph (ie
aristocrats, oppose Catholic rule)

\section{Enlightenment}
Hobbes - man selfish interests, BUT capacity to REASON and realize collective
strength is the safest for all.   So Hobbes actually is pro-monarchy b/c
stability.
1616-1633 Gaelio battles Church.
Spinoza - Dutch Jew.  Independent path.
Locke  - man is individual. Different between richest and poorest is only
education, wealth ...   Babies start with blank slate.      life, freedom,
happiness .... unclear his view of property.   At one point, each should have
enough ... but elsewhere seemed to not rule out amassing property (then called
estates ?) and perhaps first capitalist - UNCLEAR.    Also tolerant (well,
maybe not for Catholics, jews)

## Impeach
England:  evolved as method for Parliament to assure power over King. (King
can not be prosecuted for any crime.)

## Whiskey Rebellion
Poor farmers refuse to pay whiskey tax that fed govt issues to raise money.
Some violence in and round Pittsburgh.  
Whiskey Rebellion  -   Washington eventually sent 13,000 troops  to supress
'western rebellion' and enforce the tax  colllection.     But the rebels
vanished into western PA  hills.    No further attempt was made to collect the
tax.  
Who cares? Federalist party and idea of stronger
central govt began to disappear . Until the Civil War, local and State's
rights ruled the day., 

## Alien and Sedition Acts - 1797 (Adams)
Unconstitutional, but based on perceived threat from French revolutionaries
and fellow-travelers to topple Federalist govt (Adams), was seldom used  but
left a taint to Federalist brand.   After Hamilton murder, Federalist were all
but gone.   (Federalist prefered England's stability to Jefferson's support
for anti-Monarchy French revolutionaries

\section{ After Napoleon}
-   removes many parochial, arthritic European structures like local tariffs,
reduces number of German municipalities, etc.   setting environment `more
friendly` to industrial revolution.
-   France, Germany, USA ... also contributed to technological improvements,
not just England.  Empirical fact(?):  more capital per worker, more GDP per
worker. Why is Peru `poor`, cheaper to use 19th C inventions b/c cheap labor,
its GDP/Capital is about where England was in 19th.

##  Panic 1837 (1837-1848)
-   after period of rapid growth, esp. land.
-   by 1837, deep depression; one of worst in US history. 
-   US is dominated by England, for capital, for markets (cotton), and for
imports.
-   Several states default (not US govt) and state govt debt is **sovereign**,
can not sue for it in its own state court.
-   English bankers get pissed at defaults:   see what happens in democracy;
lose all values of  paying one's debts.  If US cotton crop fails, English
factories layoff -> English recession and then of course no demand for US
cotton the next year. Very tight ties bet US and London bankers.
-   Lessons?  Without hegemony, US or any country can not separate its
domestic and foregin policies.  Longer term changes, US States get out of
capital improvement projects (ie less public bonds, let private section do
this), States begin to deploy
property tax to raise revenues (and less sales of land) 
## Pennsylvania RR
- (1852-1874) pres = J. Edgar Thompson, engineer, modernizes, uses Westinghouse Air Brake.
  -  (1877)  wage cut (Depression)
  -  (1889)  Johnstown Flood Disaster (just west Altoona Horse Shoe) PRR
      built; destroys PRR equipment/repair shops
## Religion in US
-	Darwin observed human species HELP preserve weakest;  not pure survival of
fitest.

- caution on FREE THINKERS, some anti-religion b/c of hatred of 'lower
		clases', ie very conservative.

- ditto for birth control b/c reduces children of 'unfit' classes.  Spencer
		prefers 'survival of fitest':  why waste money/reforms on lower classes.

Bryan - sounded like Fundamentalist.  Not quite.   His objection to
evolution:  IF man incapable of rising above lower animal instincts, then
SOCIAL REFORMS (ie done by us imperfect people) DOOMED to fail.  More modern
(?) social reforms necessary to CONTROL worst of human animal side.  ???

Scopes -  Though Bryan initially  won in court, the decision was actually
overturned on appeal (technical issue). Then appeals court closed  case,
without clear resolution on the main issue.  Should religious doctrine
(CREATION) be allowed in public school was never argued?

-	Reaction:  North saw victory (Bryan had looked out-of-touch); became less
vigilant. South:  rise of anti-evolution.  Backlash. What had not been much of
issue, became a southern cause.  


-	Ex:  1921 - Darwin on cover of Biology books.  1926 edition -he is gone.
	Evolution removed from southern textbooks.  LESSON:   do not put your
	teachers on trial, just change books.  True today!  Report (1936) Biology
	@1900 had more science than 1936.  Creation remained LAW in many states;
	Texas much of 20C and certainly after 1980s.

  *  **J. Howard Pew** (Sun Oil) capitalism and religion do NOT conflict.  Use of
      religion in conservatism. Prior mostly just rich, anti-New Deal, or
      ideology (Ann Ryan, a few university profs). Pew wants return to
      fundamentalism.  Opposes Niebuhr and liberal Christian ideology.

      **Billy Graham** (1955)

**1917 Immigration Act** (after US enters WWI) deport immigrants criticizing US (target: reds)
**1918 Sedition Act** prison anyone disloyal to flag or US  (Debs et al)
**1919 CPUSA forms** next outlawed, but ...
**late 1919/early 1920** AG Palmer (a democrat) Raids, to deport alien
Reds.  Begins 2nd anniversery of Bolsheviks. Deportations mostly
blocked; attempt to include US citizens.

1920s - fewer US government threats, till 1930.
1930s - various Congressional attempts, leading to 
**1938 HUAC** formed
1948 **Mundt-Nixon** attempt to outlaw CPUSA; though Nixon disguises. (Senate does not pass)
**1950 - Internal Security Act, McCarran** (people lost jobs, deported, jailed).
1939 - 1950s US govenment obseesed with deporting Harry Bridges!
(became us citizen: 1945) And this was mentioned Congressional debates
of above. SCOTUS overturned one deportation order.  Then US said he
lied; ended 1955, judge US failed to prove he was member of CPUSA, though CPUSA was never illegal!
**1940 - Smith Act (Alien Registration Act,** again Bridges was target)
but includes one last clause: teach or advocate overthrow of US govt;
conspiracy. only portion not dealing with immigration added at last
momment.
**1947 - Taft-Hartley**, labor leaders req'd to sign annual statements not members of CPUSA!

12 MARCH 1947 **Order 9835** Truman wants to outdo his anti-communist
political foes (Parnell R-NJ), triggers investigate of 4MM civil
servants, charges against thousands; fired 379 ppl and found zero
spies.  Consequences of Order 9835, CIO begins to rid its of 'red
taint' and expelled unions, including Bidges' ILWU in 1950.  CIO
General Council: **Aruther Goldberg** claims if one's views align with
CPUSA then you must be one. Guilt by association.  Even ACLU expelled
Elizabeth Gurley Brown (1940), openly communist and even ACLU adjusts
rules to say Communists (as well as KKK, Nazi...) not welcome as
members.

(There were smarter people, especially judges, who spoke out on how
these laws violated civil rights.  But the heat of the times usualy
prevailed.  Later, a few even regretted distroying ppl and the party).

**1947 Nixon enters US HOUSE** brutual attact on incumbant, like same in 1951 (Helen Douglas)Senate race.  Tricky Dick smears ppl with communist label; knows false; just wants to 'win'
**July 1948 - 11 Communists indicted under Smith Act (NY)**, found guilty, SCOTUS oks as reinterpreation of 'clear and present danger' (Hugo Black, Douglas dissetn)
**1948 election** Wallace refuses to repudiate CPUSA support...; thus increasing Truman's anti-communist credentials and T's suprise upset election win.
	**Alger Hiss** stellar foreign service credentials (Harvard, SCOTUS clerk, several WWiI conferences, UN..) accused by W Chambers.  Hiss knew Chambers by a different name; said he did not know = perjuy and 44 months in jail!  Even HUAC wanted to drop this;  Nixon saw gold.
	
1950 International Security Act (McCarran) - passed after Korean war starts.  Commies must register; deny them passports; evict alieans ..... better politicans knew all this violates civil liberties.


McCarthy - Till Feb 1950, only thing he did was was get sugar controls lifted for his friends at Pepsi.


### Churchill
Boar War, captured.
Eventually (1911) joins PM Asquith gov't (reformer) in Admirality.
But in 1912, Chur changes from reform to hawk.  Held various gov't positions
prior to and though WWI. Is responsible for plan to send army into Turkey via
Dardines, but was removed and apparently others also responsible. Eventually
led troops in France; thinks about air force; feels generals too tied to past
(ex1: General Haigg);  did not want harsh terms for Germany. Lloyd George is
PM during WWI.   Churchill has many ideas and willing to try.  This can ruffle
old guard.

Churchill is also man of EMPIRE.  Couldn't understand why Irish didn't want to
remain in Empire or Arabs did not like Balfour.  Mostly certainly
anti-Bolshevik and wants army to remain in Russia.  Later, Churchill would
oppose laws to ease control over India and was behind the times even amongst
conservatives who understood the world was changing.

1924 - Baldwin is conservative PM and Churchill is exchequer. seeks gold
standard.

Chamberlain, Torry, PM in early 1930s.   But Churchill is out ... has ruffled
too many feathers. Spends 1930s as civilian, writing books, articles.  In 1932
had set meeting with Hitler, later did not show.   Was not alarmed when Hitler
first came to power (didn't like him, but did not see crisis.)   This would
change in next few years and Churchill became one of the first and loudest
voices for Britian to rearm, be prepared ...
APPEASEMENT .... was not single event.  The dominant view in 1930s England,
but to disaarm. Not build up military.  Chamberlain consistently tried to
write off fears of Germany; not rearm, not prepare even manufacturing for a
war.   This was dominant view.

By late spring 1940, no one could deny war was imminent.   At the time not
all clear that Churchill was best man to take charge.   Many thought he was
just hot head though he had many skills.   The #2 choice (or was it the #1
choice) declined the job.   Churchill now PM.

War government with Atlee (Labour), but WC is man of action and he set the
tone/even the frenetic pace of British govt til 1945.



\section{Ludendorff}
-   6/14/1914 -assassination \
-   Schlieffen Plan - Paris in 4 weeks; then Russia in 4 months;  Route through
Belgium,  not directly from Alasce into France b/c too well fortified.  But
Belgium resists more than expected.   Gen Ludendorff uses new gun and breaks
through.  https://en.wikipedia.org/wiki/Schlieffen_Plan
-   But Russians move too soon.   DUO of Ludendorff and older, aristocrat
Hindenberg defeat Russians by analyzing the two Russian armies and defeat
them separately. **Battle of Tannenberg**   However, what appeared as military success
violates Schlieffen Plan.    Germany faces  **TWO FRONT WAR**  Argument
Germany could have sued for peace and everyone could have gone home.
-   **Rathenau** Jewish industrialist; brilliant planner; and keeps Germany
    economy afloat.    Not why did the war take 4 years, but how did Germany
    survive for 4 years.
-   East or West, Kaiser dithers between 1914 and 1916 while military asks him
    to choose which one first.  Falkkenhayn (military leader in charge) says
    East; Ludendorff says West.
-   Faced with no choose,  Falkkenhayn devises Verdun Plan, control area
    around **Verdun** and bleed the city dry.  Falkkenhayn [^1] is realist and able
    general, but this is a Military failure;  almost equal deaths; pointless
    as French General activates superhuman logistics effort.  Falkkenhayn now
    replaced with Ludendorff.  Post Verdun Ludendorff + Hidenberg as figure
    head in control.  Will control army + govt as effective military
    dictatorship. :    
    :[^1] FALK also sought political way to end war; Russia was not favorable
    and German diplomats not eager;  another failure.
-   Turnip Winter (1916-17)
1916
-   British blockade Germany; Germans down to 1000 cal/d, starving.  (German
army always had enough to eat, unlike Russian army, German general and
aristocracy clueless about actual conditions in population.  England has
enough food sources no starvation.
-   Haber tells Ludendorff can produce enough fertilizer or poison gas NOT
    both.  His wife is so upset with what her husband does she commits
    suicide. 1918 Germany.
-   Whatever Ludendorff asks, the German people provide.   It was never for
    enough for Ludendorff who had no understanding of people, soldiers, war,
    death, starvation.  He is to blame; not the German people.  Ludendorff
    regarded as brilliant tactician (Take that hill!) but absolutely clueless
    how to defeat an army or win a war.       
    Russian General Brusilov defeats Austrian army (date, significance?)
-   Claim in 1916 Germany could have very reasonable peace deal.  Ludendorff
    either intimidated a weaker Kaiser or fooled him and the industrialist
    class, as well as the people that great victory lie ahead. A big lie.

-   March '18
        German military almost breaks French-British line in France. High
        point.
    -   Oct '18 German Revolution begins?    Reason why Ludendorff sees loss?
	
	1918-1933, Germany opens in many ways, but numerous financial crisis (inflation, inability to pay reparations), country seems divided between far right and far left.
	### German PM
- 1918 Ebert (Social Dem)
- 1924 - Dawes Plan (US banker, arrangement to suspend re-payments to 1929; borrow to get back on feet)
- 1925 - Locarno Germany less outcast; finalize western border (never finalized eastern border)
- 1926 - joins League of Nations
- late 1920s - French foreign minster **Briand**, German foreign minister **Strasemann**, nationalist, but able to work together for peace; but Strasemann dies age 51 1929.
- 1928 - elections, Hitler's party only 3% of vote; many think he's done.
- 1929 - Young Plan, attempt to restructure Germany war debt (can borrow short-term)
- late 1920s German politics becomes conflicted.  Hidenberg is President and would like Kaiser to return.  Strong right win among establishment;  and then there is far, far right Hitler, who pledges to gain power through elections.  Meanwhile his Brownshirts, Stormtroopers increasing sow random violence; always blame it on far left, jews, ...  German communists / socialists never work together (former wants revolution, not anything incremental) 
- 1930 election:  **Nazi 18% (107 seats), Communists 70 seats)**
- **Depression** hits Germany very hard. Many say it is western banks, gold standards.  **autarky** (withdraw from world economy, self-sufficient).  France offers loan to Germany, but far right strongly opposes:   get rid of Versailles Treaty.
- 1931 - Germany borrowing heavily of short-term loans to pay reparations, but as forgign banks relucatant to borrow more, gold leaves Germany central bank.  German interest rates are high, b/c any free money moved to Wall Street.
- 1930-32 Bruning Catholic (more conservative than Protestants), very smart, but opposes French loan, stauls and wants to plead poverty to get rid of Versailles and appease his far right. (Loan would be worst thing.) Keynes idea to **spend** out of depression ignored by country's fear of hyper-inflaction.  Bruning increasingly very unpopular.   Hindenbrerg operates by decree with tasid approval of Social Dems (Hinb hates them).
- **June 1, 1932** Hindenberg ask Bruning to resign. Two important players:  **Schleicher** has been Hindenberg's right hand man and in the shadows.  He is schemer. **Papen** is vain aristocrat, mere puppet. Both take a turn  and fail (cannot get majority in Reistat) Hitler continues to whip up settiment:  violence in Prussia
First Papen is made Chancellor, until Dec 3, 1932.   Then Schleicher is Chancellor;  Pappen covets perks of power and  .

- **jan 23, 1933** Schleicher forced to resign (only 2 months in office)  Pappen has convinced Hidenberg that he can control Hitler (and has secretly met with Hitler).
- **Jan 30, 1933** Hitler is Chancellor, with Pappen as vice-chancellor and minimal Nazi in cabinet. 

- Rmk:  Treaty of Sevres, Turkey/Ataturk stands against and gets more favorable Treat of Lausanne. Mussolini and now Hitler and many Germans admire strong Turkey and Ataturk.


## Durrs of  Alabama   "Outside the Magic Circle"

Virginia Foster Durr (1903- ) remarkable; able to cast aside upbringing.{{{
Influencial whites through racial, liberal causes of 1st half 20th century.
Knew:    Mary McLeod Bethume, Studs Terkel, Linus Pauling, Eleanor Roosevelt,
oppposed Poll Tax; apposed HUAC;  apposed Truman's loyalty oath (1946 -
claimed it was to get ahead of HUAC and NJ Rep Parnell Thomas); supported
Henry Wallace; brother-in-law Hugo Black (liberal ??)

Not merely her views, but she (and lawyer husband Cliff Durr) took active
stances that made enemies; hurt them financially; politically.   Remember
taking a stance agasint poll tax in Alabama will not make Senator xxx
(Eastland) like
you, who in 1941 called her to testify and asked "Are you a Communist?"  (1st
whiff of what was to come.


1938 - Radicalized by LaFollette Hearings re:  crushing labor unions.
New Deal Washington DC draw in people with idealism, ideas and cultivated
social environment that encouraged BEST in professionals who joined New Deal
(everyone cleared out when FDR died)

SCHW: Organized black and white conferences, such as one in Montgomery ALA, attended
by Eleanor, and condemned by BULL CONNOR

Highlander Folk Camp; 

1941 - Claude Pepper - FL - sponsor anti-poll tax

Durrs targeted by FBI, red-bating; Cliff headed National Laywers Guild, that
NIXON attached. Cliff, fired by Truman's loyality oath; represents people
fired becuase of the oath.  Cliff, who no longer can hold federal job,
represents poor blacks.

With Linus Pauling, signed petition to not bomb above Yalu River.   This led
to her being ostracized in high of red scare.

1955 - Along with local activist (Nixon?), Durrs help bale out Rosa Parks.
SNCC;

<!-- }}} -->

## Rise of Hard Right:  anti_New Deal.
  *  hate National Recovery Act's price controls; profanity to business.
  *  Assorted groups in 1930s-1950s, Leonard Read (Chamber of Commerce, vast
      networking, Foundation for Econ Education) Liberty League (duPonts)
      National Association of Manuf.  These are not nice people; have agenda.
      Barody (American Enterprise):  soft touch, `policy papers` to give to
      Congress.  Others:  Eventually pursue mass audience, get mass recruits
      (not just business or ideology or religious)
  *  By 1978, Powell memo; Kenysian not working; corp MUST get into poltics.
      First use of PAC. Coors.   Prop 13 (Laffer had hand?  cut taxes, watch
      GDP soar).  Heritage Found (Coors).  Jack Kemp:  stop regulating, cut
      cut cut; GDP will be unleashed. 
  *  More post-Powell:   Business Round table (soft touch, CEOS only; direct
      reach to pols, both D and R;  and Carter, NO social issues, Softer touch
      but same as Bouleware or Goldwater)  Chamber of Commerce (not big biz;
      "entrapenues",   Amyway - DEVOS - "American Way".   Anyone can join C of
      C. more aggressive, freedom and capitalism; populist; more like political
      party than lobbyist)

## Smith Act (1940)  advocate, even teach, overthrow US govt is criminal
(1958) SCOTUS:   standard must be call to action.

Esther Cooper Jackson (1917-2022), 
-   South, Brooklyn, Detoit
-   "Freedom Ways" (editor)
-   worked with W.E. DuBois  (SEE bio by https://en.wikipedia.org/wiki/David_Levering_Lewis 
-   1940 AG Tom Clark, South Negro Youth C... (later SNCC) is subversive.
-   [https://en.wikipedia.org/wiki/Esther_Cooper_Jackson
    ](https://en.wikipedia.org/wiki/Esther_Cooper_Jackson  )
-   National Committee to Defend Negro Leadership; Families of Smith Act

## Ayn Rand, novels, 1943-1957.
(1958) SCOTUS:   standard must be call to action.
  *  "common good" is awful |  self-interest paramount |  it is better moral
      code than even religion (?!)
  * property:  absolute right to do what you want w/ property.  No govt
      interference  Business loves her.

## Sen Taft, isolationist
1938 - New Deal stirs hatred of rich | will bring socialism; isolationist.


##  Strategic vs Area vs Precision Bombing
- Did not work, intent:  limit civilan casualties, we are not like immoral enemy.
- This view changes!  Desden (US Gen Spaatz; Feb 1945; Secy of War
  Stimpson kept out of loop; did not like destruction of glorious
  city; or needless deaths; a moral man and concerned with image of
  US).  Lovett limits info to this moral boss Stimpson; just says
  "precision bombing" - a lie.
- Tokyo (March 1945; firebomb, Gen Lemay new to Japan; told he must
  get results or lose job; and quickly realizes stategic bombing not
  working; will need to invade island; tries fire - naplam - noting
  Japanese cities mostly wood; goal: weaken moral)

##  Decision to Drop A-Bomb
-  No real 'decision', it was the entire reason.
-  Truman not truly lead actor;   aruge that Stimpson, Staaz and Toto are major players
-  But, WHERE to drop Bomb?
-  (see next) As it became clear, Japan was not doing to surrender and
   Am public did not protest Dresden, much debate of where.  Need for
   Japanese to see clearly the power; dud would not do (fear that a
   dud over Germany and Germans would figure out how to make it!  No
   such fear with Japan) A solely military, strategic target would not
   demonstrate full power of bomb. Nor would anything of reinforced
   conceate Had to a city; not near mountain.  And because of
   imprecision of bombing (despite new Nordon scope) had to aimed at
   center of city.  Even scientists acknowleded this logic.  Both
   Conant and Opie silent, however, about role of radiation, though
   they know it will happen)

##  Unconditional - notes from book; Japanese surrender.  (SEE also ...)
  * Work with japanese 'moderates':  US Amb toJapan in 1920s, "Jap" experts: 
       Grew and Dooman (but 1920s Japanese rulers very different  from
       militarists) ; Hoover (!) - Stimpson Doctrine, based on observations of
       1st round of Japanese aggression, 1931: moderates will soon prevail.
       FDR had provoked Japan??
  * Stimpson (Secy War, WASP, but deep conscience esp civilian bombing
    deaths); Gen Hap Arnold (Army Air), Gen Groves (Manhattan,
    energetic and efficient, but fat, Secy Simpson leaves him alone)
  * Stimpson's `assistants` McCloy, Lovett (advisor re: air power,
    advocate), Bundy (S-I = Manhattan, advocate intn'l arms control to
    prevent next war); All highly compentent.
	
  * Example of Stimpson; To explain A-Bomb to Stimpson, Gen Groves used greek myths as analogy,  suddenly Stimpson gets it!
  * Russia Hawks, GOP & Hoover, Russia will dominate a weak China; must
      negotiate with Japan asap before Russia enters war against Jap. Russia
      is now bigger fear.  On other hand, as against Hitler, let Russia take
      the caualties to fight Japan.
  * Other US factors:  US pop is war weary;  GOP pillared Wilson for pursuing
      14th points rather than unconditional German surrender.   Iwo
      Jima/Okinawa (April - June 22, 1945): ferocious Jap fighting. 1942
      elections:  Dem lose 45 in H, 9 in Senate: New Deal in retreat.
  *  Marshall (Army Chief of Staff) `thinker`:  invasion necessary for Jap
      surrender.   Stimson (War), Know (Navy)
  *  Japanese:  Togo (Foregin Minister): end war NOW, but all other seek
      a battle victory before negotiating.  Military (fight, fight till win):
      plan to mobilize entire nation, including suicides.  Generally, Japanese
      feel time on their side,  attrition hurts US more than Jap; buys time.
  *  June 8, 1945.  Susuki, now head of state, reaffirms fight, not negotiate.
  *  Then Kido (head of govt) plan (doomed) withdraw from former EU colonies, 
        ask Russia to mediate; this is "daring" attempt to modify Jap Army
        plan. didn't happen.
  *  June 18, 1945  consent for delegation to Moscow, but Jap Army/Navy may
      contact Russia  ONLY after Japanese battle victory.
  *  Hirhito
  *  April 1945, Secy War Stimpson tells Truman of bomb; (As Sen Truman had been poking close to secret funding A-Bomb, in 1944;  Stimpson then had cut him off)
  *  Even, After 2 bombs and Soviet invasion,  Japanese top leaders deadlock 3-3 on surrender.  (Military wants to fight)
  



\section{US Policy - end of WWII }

Fulton: Churchill speaks for war; at time many criticized; Truman, present,
also not pleased.

1946 - most US scientists:  what have we done?
DEBATES:    Share knowledge? Cooler heads knew Russians would catch up; but
hawks rise.
Truman disliked Oppenheimer;  things Russians will "never" catch up.
Influence by his own racial prejudices.  Truman captured by hawks does not
even want to share with British.
Acheson-Litelton (influenced by Oppenheimer) - share bomb with world, to
manage it.  Barauch presents to UN (6/46), aging, poor choice, did not believe
tenets himself.
AEC:  civilan control of US bomb, not military.


1947 HUAC / Hollywood, Reagan 
-   1930s HUAC formed to investigate German Bund and Communists;  soon to zero
  in only C-.   1938 foreign agents to register, only actual legislation
  enacted.  Martin Dies (D-TX) anti-progressive soon becomes Chair and uses
  for power.  HUAC reauthorized every year.
-   Hollywood unions > 1935, mixed:  some good, some not;  SCOTUS:  Hollywood
  IS subject to 1935-Wagner Act (artists originally exempt)
-   Many in Hollywood sympathetic to progressive causes (range, in
  dedication). Several wrote scripts with references in some way to good
  causes, in movies otherwise very non-political.  Smallest of big 5 was RKO
  and most liberal:  Dore Schary "Until the time it is proven that a C-
  dedicated to overthow of gov't, I can not determine any ground for hiring
  but, by the man's competance."   But many faced backlash from Right hysteria
  for their views.   Others supported by money, by organizing others, by penning
  comment here and there.   Maybe one or two card-carrying C-, but most
  sympathetic to various progressive views, or simply wanted their work to be
  truthful, some simply anti-Nazi.

-  evil:
  Ronald Reagan ("friendly witness")
  Hedda Hopper, vicious anti-New Deal
  Tenny - vicious Calif state Rep

-   good:
  Lester Cole - objective film re: Burma
Lillian Hellman - sharp tounge, anti-Huac 
Edward Dmytrk, director, included religious toleratance (Crossfire, 1947)
Emmet Lavery, lawyer, 
Committee for 1st Amendmand
Dorothy Parker, Edward G. Robinson, Melvyn Douglas, John Ford



1947
Awareness European economy poor.  Spring ==> Marshall.\
March '47:  Loyalty Order, signed by Truman!  Hoover, Ambassador Hurley
(China) disloyalty has entered US gov't (!?) Chill falls over federal
employees, finger prints, a few fired.

\textbf{ National Security Act}
-   Military under unified (ref to 1941 attackZ), civilian command.
-   War Department (army) + Navy; both military at head  ==> Defense Dept (civilian)
-   National Security Agency:  coorindate, military + foreign policy (vs.
State Dept ??)
-   `world policeman` enters debate in Congress.


## US, WWII VP Wallace, Am style facism.
- 1944?   "build a wall around the US so high and so secure that not a single
		alien or foreign refugee from any country ... could possibly scale or
		ascend it."   Senator Reynolds (D-NC, Military Affairs Committee,
		isolationist, racist, wealthy; "Fortess American")

- Henry Wallace,  April 9, 1944: 
-
- "The American fascists are most easily recognized by their deliberate
- perversion of truth and fact.   Their newspapers and propaganda
		carefully cultivate every fissure of disunity, every crack in the common
		front against fascism. They use isolationism as a slogan to conceal their
		own selfish imperialism.  They cultivate hate of and distrust of both
		Britain and Russia.  They claim to be super-patriots, but they would
		destroy every liberty guaranteed by the Constitution.  They demand free
		enterprise but their spokesman for monopoly and vested interests.   Their
		final objective toward which all their deceit is directed is to capture
		political power so that, using power of the state and the power of the
		market simultaneously, they may keep the common man in eternal subjection.


##  GE Strike, Boulware
-   1946 strikes catches GE off guard (huh?).   Emerges Boulware:  GE is boss,
    not union.  You take what we give; no matter how long you strike.

##	HUAC
-	claim:  there really was effort by CPUSA and "popular front" to disseminate
organizing, education, labor activities.  But overthrow?? 
-	1947, 1948 (?) investigates communist influence in Hollywood (actors,
directors, writers ...)  Vicious.   Many those targeted had liberal leanings or
depicted another side of life in their works, films  themes like religious
tolerance, anti-Semitic (ex:  John Wayne film
ALSO shows heroism of fighters in Burma?)   HUAC forced you to take
stand or they would end your career.  Some, including an RKO executive Dore
Schary , stood their ground ("Until the time is proven that a Communist is dedicated to
overthrow gov't,  I can not determine any grounds for hiring but the man's
competance.

##  William F Buckley emerges:
  *  pro-McCarthy
  *  anti-'elite' liberal education
  *  labor union "monopolies"
  *  he seeks non-business adherents to conversative (more ideological)


##  John Birch Society, real person
-   1939 rural Georgia, bible-thumping family, graduates college.
-   1940 July Shanghai China as missionary
-   1942 by how fluent in Chinese, saving souls, he works among Chinese;
meets Doolittle. (APR).   In July '42 Flying Tigers (volunteers) now called
"US-China Air Task Force" (Chennault) and in '43 becomes 14th Air Force.  To
survive, Birch joins US army in China.
-   1943 Birch in Chansgha, behind Japanese lines provides intelligence re:
Jap troops, status of airfields.
-   1944 (July) Chennault awards Birch metals for his work.  Birch seems to excel at
everything he does. (Oct) Vinegar Joe is out. Gen Wedemeyer in (too
sympathetic to CCK)
-   1945 (late August) war over.   Birch and party stopped by Communists (not
something unusual or alarming).  But Birch is tired, weary from war ... makes
threatening move and is killed.  A tragety , but not a hero. his fault.
-   AFTERMATH:  Wedemeyer talks down to Mao, bad move.   Mao protests had
saved dozens of American pilots, knew nothing about his indicident.   Beside
you are operating in our country, area controlled by us, why didn't you inform
us of operations?   Later testimony, Birch did provoke.  Birch knew Chinese
well-enough not to act this way.    Later, US army does
NOT award medals, not a hero, US & China were on **same side**    Zhu-de does
investigate writes report.   Mao does take incident seriously, but facts point
to Birch's own error.    US Wedmeyer and Ambass Hurley ... choose CKK.
Americans just too arogant.    **US-China cooperation effectively begins to end.**

-   Sen Knowland, anti-communist since at least 1946, makes speech in 1950.
Birch's mother endlessly lobbies.    First American death of next war?   Just
spirals on and on.   Welch, of Sugar Dadddy, Junior Mints, Pom-poms,  looks
for symbol.   Welch part of well funded effort..... 

-   1952 Taft also sees communistis everywhere.  But Eisenhower gets
nomination.   Birch Society forms actively in 1957? 1958?



## IKE and presidental power
John Foster Dulles dies in June 1959;  thaw begins in East-West. Major
conference set for 1960, Paris.    Failed. 
IKE  even was tiring of Nixon's  infatuation  with seeing REDS everywhere.
NO.  The event was U-2 shot down.  
Message by You: IKE *seemed* to have some
decent instincts. But he also tolerate or set the stage for all kinds of bad
shit., Saturday, December 12 2020, 12:33 PM IKE *seemed* to have some decent
instincts.      But he also tolerate or set the stage for all kinds of bad
shit.  

One legacy: creeping Presidental power to make war. He
got Senate approval for various forgotten incidents in Taiwan, Lebanon that
would allow future presidents to have all kinds of undeclared wars., Saturday,


Adlai Steveson: After Senate passed one of these 85-3,
Congress has given president a "blank check".,

## Goldwater:  1957 hearings.
Hates unions, "freedeom", no one should challenge the boss.   Walter Ruether
at hearings.

##  JFK
  -  To balance conscience and job, he promised to resign if ever conflict!
-	Both JFK and esp HHH supported clause  allow govt to arrest/detain
subversives in times of national crisis.   1962 Cuban Missile,  FBI Hoover
kept list and called many such subversives (anonymously, to track them). JFK
did not declare emergency.  Bernstein's parents of (Berstein/Woodruff)
receieved phone calls.

##  Watergate
REF:  book Goliath
1972 - Watergate babies, young, `liberal`, college-educated and definitely anti-war.  Replace
old man, Wright Patman (D-TX), 1928-1972, who believed in preventing monopoly
power.  He was last of generation like Brandeis who oppposed bigness,
concentrated power (though may be different reasons).  In 1930s, he passed law
to prevent A&P, chain store, from offering various discounts, rebaits that
made mom&pop difficult to compete against.  He had no problem with
"efficiency", or that mom&pop could offer better service.  He opposed
concentrated power to UNFAIRLY change playing field.   That was "fair trade"
meant in 1930s.

Both Hofstader and Galbrieth praised big business!   H- argued American
triumph & prosperity due to big corporations.   G- did not focus on `class
struggle`, is that Liberal means?

A&P law become symbol of opposition to gov't. :
deas of Limiting big business persisted to 1960s (by mostly old men).   Began change
in Democrat Party away from working people, fairness, economic issues.

## Reagan
- even in 1940s did not associate "liberalism" as first step to Communism, but
  "proud" to keep Communists out of his union.   But in '50s more
  pro-business, against govt intervention'.  Goldwater speach "time for
  choosing" said nothing about social issues.  By 1966, sees opportunity to go
  attack to attach LBJ's great society and SOCIAL ISSUES for first time
  (crime, welfare, persmissive society criminals have more rights than victims
  ) Not racist, just govt should have no role in making balance. Voting Rights
  Act "humiliation"  for South;  he opposed it b/c opposed to gov't
  intervention, not racism. His pro-ERA, pro-abortion, tighter gun control
  positions as gov. would all vanish in 1970s as *single issue social issues*
  backlash.

- saint today, but in 1980 was 3rd choice of GOP.  Party split, grudingly
  adopt him after success in primaries. vs. Goldwater, Reagan was "sunny", BG
  "dour";   policies are same.  vs. anti-Red 1950s, he was (now) upbeat,
  folksy.   So sunny he could rail against 'reverse racism', 'affirmative
  action' and turn it into a dog whistle by emphasising *just want to be fair*
  and *without Welfare Queeens*   (I don't remember him as a dog whistle. )

- After tax cuts, he had to quietly walk it back and raise revenues (vs bigger
  debt).   And vs his retoric , he could embrace Gorbachov.  He supported
  apartheit in S. Africa, Marcos and Contrats with weapon sales.   "Freedom
  and democracy" justified everything.

- pro-abortion as gov, but anti- as Prez, insisted VP Bush drop pro-abortion
  position when became running mate.

- pro-immagration, but not for victims of Right Wing violance in L. America.

- The New Right never accepted Reagan;  saw religious zealots as opportunity
  to benefit from anger.   Never pro-gay (supposedly he & wife had too many
  Hollywood ties), but never fervently anti-gay (AIDS ... just did nothing;
  did not rail against it)


- Claim:  by 1988, hard-right was not happy with Reagan (b/c he backed off
  lower taxes, deep budget cuts, he met with Gorbachov, did not push for
  anti-abortion Amend.)  right wing had great expectations.   Reagan was good
  politican,  if proposal not popular he quicly backed off or blamed it on
  someone else.

- So Bush, same policies as Reagan, became target of far-right, way to
  crtiicize Reaganism without criticizing Reagan.


## SCOTUS
    - Did you know this ???     From SCOTUS oral arugment ....   "political
  promises"    are not contracts, not enforceable,  not legal justification to
  replace the politician!

##  Mon  14 Dec 2020  50 years from now, today will be remembered as ....
 - Day USA passed 300K covid deaths
 - Day USA began vaccinations
 - Day AG William Barr resigned
 - Day Electoral College voted Biden President.
 - Day American people began to realize EC must be replaced.
 - Day American people began to realize Constitution out-of-date.
 - Day American people began to realize how much damage Trump had done to
     USA.
 - Day American people began to realize USA is in decline.
 - Known for some other reason.
 - Long forgotten day.



##	Lorraine Hansberry (Rasisen in the Sun)
-	1930s, raised in area south/west of Washington Park (between Cottage and
Grand (MLK))
-	some areas black, some white .... Woodlawn all white.
-	father chopped up apts to make room for steady flow of north-bound black
migrants.  Made him rich.  but ran into racial covenants.  Sued.  (He is the
new LANDLORD as bldg change owners).  Very ambiguous to me:  what were racial/economic boundaries?
-	attends public schools; mixed white;  Lorraine is cursed, spit upon, etc
for father's suit against covenants.
-	2 older sisters attend Howard U; `popular` rich young black women; arrive
with multiple trunks in toe.
-	not so, Lorraine; attends U Wisc; scholarship;  contends with
	implicit/explicit racism; blossoms into rebel but endears all who come
	within in her reach.  eventually Communist.


\section{finance}
-   1987 crash?   not due to economic conditions;   failure of Black-Sholes
model (buy puts, 'insurance') to protect against falling markets.   Can't do
that when everyone is doing same; and market is crashing.

##  Eugene, OR
Judge Alfred Ted Goodwin, 1923-2023
father was Baptist minister;  
-   ordered cross removed from Ore. hiltop.
-   beach bet high tide and vegetation is PUBLIC (1964)
-   Nixon appointed to fed bench.
-   favored **federal** enforcement to protect Spotted Owl
-   forcing children to recite "one nation under god" violates separation of
Church. (unfortunately, reversed in separate case when 'teacher led')
-   also branded cattle (man of the west?)
