---
title: Loose Leaf
date: last-modified
---
/home/jim/code/docs/misc_files/010_R_loose_leafs_HTML.qmd
<!--
      HTML VERSION of Loose Leafs

      Last Edited:   2023-05-22 

-->

##	Loose Leaf VOLUMES

####	Volume 01 - CLI Skills

-	Android (adb, fastboot)
-	CVIM
-	CURL (SEE:   API, R-misc, API Notes, OAUTH2)
-	GIT (SEE:  index c)
-	JSON (SEE:)
-	LATEX	(SEE:)				(ALSO:  WIP)
-	MAKE  (SEE:)
-	REGEX/GREP		(SEE:  ZSH for glob)
-	SEARCH				(SEE:  INDEX CARD)
	-	Gmail | Github | DDG | ...
-	TMUX
-	YOUTUBE-DL ( Now:  yt-dlp;  SEE ~/bin/)

####	Volume 02 - LINUX CONFIG/HARDWARE
-	Linux Config - General
-	GRUB, X11
-	OS, OS-tools
-	Hardware ChromeBox ChromeBook Laptop
-	PHONES	Other eToys

####	Volume 03 - Neovim/Lua | nvim-R  
-	(SEE:  Index C; notes)

####	Volume 04 - ZSH
-   GLOB/Zsh quantifiers

####	Volume 05 - MATH, ALGEBRA
-	Linear Algebra
-	ML
(if R code, put into R LL [^1])

####	Volume 06 -	Statistics
-	Classic (sampling, t-distribution etc)
-	Regression
-	Baysian
-   ML

####  Volume 07	-   R & NSE	

####  Volume 08	-	R:	BASE and Other R skills 
-   Follows Advanced-R Book 
-   Base R:  see individual git repos/index cards/Tech Notes

[^1]:		LL = Looseleaf	
<!--
vim:linebreak:nospell:nowrap:cul tw=78 fo=ntl foldcolumn=3 cc=+1
-->
