2023-08-26  

## Life/Job Notes, 2023-08-26 

1.  Costs:  Monday will go to Patrick Olson to see about `repair costs` and `junk it ` costs.  When I called about oil changes, he said he had 3 week backlog and so entirely possible he's won't eeven look at car for a few days.

2.  Costs: I have plenty of insurance, but usually with `large deductibles` and `NO collision`.   Expect liability for `red truck` to add to cost.

3.  Reason for *no collison*:  if repair cost is more than say $1000 it makes
    little sense to fix car  (original cost was $3500).  I didn't think
    *parking* would be large *collision* damage.  (*collison* sounds like,
    well, a collision).

3.  Sleeping in office last few weeks (heat) but not a wise or exteneded strategy.


5.  **Electric Vehicles** absolutely need to do research.  My monthly driving, 100-200 miles, means that OLDER, electric vehicles, with range less than 100 miles per charge could be ideal for.  I suspect most buyers, for new or used, want much higher miles per change.  Need to see if prices reflect this.

   <https://www.recurrentauto.com/research>

Not going to buy this one, but example of $6000+ used EV (car + needed repairs); 50K miles
   <https://www.autotrader.com/marketplace/buy/nissan/leaf/2012/JN1AZ0CP3CT017447?listingId=689873778>

4.  `On bright side`, this time for first time in **many years** began actively  looking for work (resumes, *contacting* people).  Though I have plenty of minuses, the area of softwareI know has fairly high demand.  (Not as high as kidneys or kidney doctors, but still ample).  There is work for a regular company (on-side) and then there is `project work`; which is often remote via internet or on-site.   Eugene is not ideal place, though I remain very comfortable here.  Important:  must stay with this and NOT be distracted by *cars*.
