
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 10pt   
geometry: margin=0.5in,top=0.25in   
TAGS:  render,knitr
---

\textbf{PURPOSE:   }

knitr any of (.md, .Rmd, ....), even plain old .md files
Until learned more latex, pandoc, and pdf/html outputs, USE KNITR

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
```


```{r library, include=FALSE		}
file  <- knitr::current_input() 
library(jimTools)
``` 



***

```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```

\newpage

```{r render, eval=F, include=F, echo=F}
file <- "~/docs/misc_files/00020_contents_storage_locker.md"
file  <- "999999_render.Rmd"
file  <- "00040_my_projects.md" 
file  <- "00020_contents_storage_locker.md"
rmarkdown::render(file,
                  output_format = "pdf_document",
                  #output_format = "html_document",
                  output_file = "./out.pdf")
                  #output_file = "./out.html")

```

