# ~/code/docs/misc_files/_quarto.yml
# For Resume:  REF:   https://github.com/rbind/yutani/tree/master
project:
  type: website
  output-dir:  docs
  render:                             ## limit dir? 
#     - "018.2_abstract_syntax_tree.qmd"
#     - "410_bquote_example.qmd"
#     - "250_quarto_cheat.qmd"
#     - "300_tech_notes.qmd"
#     - "TEST.qmd"
    - "!*.R"          # do not render
    - "!*.Rmd"        # do not render 
    - "*.qmd"         # must include after a negation

  ## project-wdie
format:
    html: 
    #      theme: cosmo
      theme: 
        -   lumen
       #   -   resume.scss
      toc: true
      toc-title: "Contents"
      toc-location: left
        #date: last-modified
      css: styles.css

execute:
  error: true
  cache: false  
  output-dir: docs
  standalone: true 
  collapse: true



