---
title: "280_emacs_notes.qmd "
author: "JR"
date: "5/22/2021"
output:  html_document
editor_options: 
  chunk_output_type: console
---

**vim** is a terminal program.
**emacs** is a gui program;  can run in terminal but better to use **emacs --daemon**

This document is about **emacs**, but written in quarto to practice quarto decorations
SEE: https://protesilaos.com/codelog/2022-01-31-learning-emacs/

::: callout-note
Note:  

i3 and emacs can conflict.    SEE: https://sqrtminusone.xyz/posts/2021-10-04-emacs-i3/ 
emacs is a gui program;  no need to run it from terminal. (Can, but not best)
vim is terminal program;  do need to run from terminal.
:::


## HELP
- help for variable
^h v  display-line-number \

^h a  evail   # any emacs/gnu topic? \
^h k  F10     # enter keystroke to see binding \

- help for function
^h f current-buffer

M-x apropos-documenation eval
M-x describe-bindings
M-x describe-mode

```{r}
```

## LEARNING
tutorial (^h t) - shows in red when evil remapped an emacs key.
emacswiki: (look for newbie) https://www.emacswiki.org/

daviwil:  emacs from scratch: videos + config
https://github.com/daviwil/emacs-from-scratch/tree/8c302a79bf5700f6ef0279a3daeeb4123ae8bd59


## EVIL
Read & re-read:  https://github.com/noctuid/evil-guide

## ELISP
Run lisp ?  or REPL:   open  ~/code/elisp_project/010_basic_elisp.el

^x p e  for eShell
^h i m Elisp RET (read manual) not working
- short guide: https://github.com/chrisdone-archive/elisp-guide?tab=readme-ov-file#programming-in-emacs-lisp
- practical: (REPL)  https://gigamonkeys.com/book/
- gnu elisp https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html 
- Toretzky Gentle Common Lisp http://www.cs.cmu.edu/~dst/LispBook/

[SICPv2](https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/6515/sicp.zip/full-text/book/book-Z-H-1.html)
[[https://www2.lib.uchicago.edu/keith/tcl-course/emacs-tutorial.html][emacs, with explanatons!]]




## Org mode
only in .org mode?
also M-x org-insert-link
[[nytimes.com]][nytimes]
	[['file:280_emacs_notes.qmd']][emacs notes]

## Watch Every Command ! 
M-x global-command-log-mode
M-x clm/open-command-log-buffer

Create a footnote: [^1]

[^1]: This is footnote one.

::: {.content-visible when-format="html"}
:::


***
::: {.content-visible when-format="html"}
:::
***

##  PDF

::: {.content-visible when-format="pdf"}
TODO pdf - fix greater than equa
  pdf: 
    toc: false
    include-in-header: 
      text: |
        \usepackage[top=.5in, bottom=.5in, left=.7in, right=.5in]{geometry}
        \usepackage{amsmath,amssymb,amstext,amsfonts}
        \usepackage{lipsum}
:::



::: {.content-visible when-format="pdf"}
Will only appear in HTML.
\renewcommand{\familydefault}{\sfdefault}
\section{R Definitions \& Examples   (TERSE)}
\section{Manuals}
\\section(Definitions}
:::


