(define-key evil-normal-state-map (kbd "<tab>") 'evil-toggle-fold)

S-<TAB> cycles
C-ENTER new line, at same level

lintr::lint()

Use these:
styler::style_pkg()
devtools::lint()
devtools::spell_check()


** FAQ

What topics does bi-weekly Admiral meetings cover?

A lot of what we make is based on the Study Design and questions being
asked in the study to prove the safety and efficacy of the drug
through something called the SAP (Statistical Analysis Plan).  So
which ADaMs, TLFs you pick is really dependent on the SAP.  There is
something called the Protocol that is a higher-level version of the
SAP which influences the eCRF (electronic Case Report Form) and
determines what data is collected.However, you will always have an
ADSL dataset!!


*SAP* - Statistical Analysis Plan |  Example: https://cdn.clinicaltrials.gov/large-docs/80/NCT04182880/SAP_001.pdf

*TLG* - https://pharmaverse.org/e2eclinical/tlg/
*R Consortium Tables Working Group*:  https://rconsortium.github.io/rtrs-wg/


How I join bi-weekly Admiral  meetings?
https://github.com/pharmaverse/admiral/discussions/2169#discussioncomment-10376594

Once you do a few more successfully merged PRs I will propose to core
team that you be included! Be great to have you involved.

<2024-07-15 Mon> - Reorganizing, in process
<2024-07-08 Mon> - Added original *Progamming Strategy* (from Admiral, .Rmd file) to this document.
- First, pandoc -f markdown -t org -o orgmode.org RMDfile.Rmd
  - Intent is to do add *my annotations*

    <2024-08-02 Fri> Attached is messy pencil sketch.
    It is my comprehension of pharmaverse at this moment: confused! It
    is snapshot in time, mostly for me not you guys. As I see it, the
    overall process is a sequence of database 'states' and
    'transitions'. The sketch should depict the tables, key fields,
    links between at each state. The specific terms (CDISC,
    derived_var_*) are less important at this level. An R or database
    programmer should readily get the idea, even if clueless about the
    context or purpose. So Admiral or other package function too low
    level for this. Next: I want to fill in the gaps, errors roughness
    so I gradually see how the pieces fit together. If it will be
    useful as REFERENCE, I will be happy to aim for that. Now I am
    just trying to figure out what I know/what I do not know. Most of
    this from Coursera and two recent videos you and Ross did. Then
    github package documentation begins to make much more
    sense.

    <2024-08-21 Wed>
    Updated Plan for Issue # Situation
    
    SITUATION NOW:

1. *data/*.rda* Path  to created data.
2. *inst/example_scripts/\*.R*   Path to  \*.R files,  create \*.rda files.

AFTER:

1. (NO CHANGE) *data/\*.rda* Path to original data. 
2. (NEW) data-raw/\*.R       Path to new code. 
3. (REMOVE?) inst/example_scripts/*.R   Path to old code.


To effect this, propose these  intermediate steps:

1. (Temporary) Add: old_data/ folder to hold copy of \*.rda files. 
2. Empty: data/  .
3. Run: new code (data-raw/*.R)  New data saved in data/*.rda
4. Run: test.R (or equivalent as testthat) verify old and new code produces IDENTICAL *.rda files.
5. Pause for review/discuss 

As a final step

1. Remove folder and old code inst/example_scripts/*.R  
2. Remove old_data/*.rda   (copies of orginal data)
3. Remove test.R, 
4. PR


As initial run through:
1. Do this for example_qs.rda ONLY
2. Pause for review/discuss.
3. Then to for all remaining *.rda files

How to document this?




* My Notes

------------------------ Organizations

** Terminology:  organizations & standards

- *PHUSE (UK)* - lots of conferences| [https://phuse.global/Communications/Webinar_Wednesday] [https://phuse.global/Working_Groups][PHUSE Working Groups]
- *pharmaR* (original attempt)  -> pharmaverse
- *R Validation Hub* (~50 companies) |
- *R Consortium Working Group* [[https://rconsortium.github.io/submissions-wg/][R Consortium]]  [[R Submissions Working Group] [https://rconsortium.github.io/submissions-wg/]]

- *CDISC Glossary:*  https://evs.nci.nih.gov/ftp1/CDISC/Glossary/CDISC%20Glossary.html
- *CDISC Video Primer:* (how good?) https://www.cdisc.org/primer

*SAP* - Statistical Analysis Plan |  Example: https://cdn.clinicaltrials.gov/large-docs/80/NCT04182880/SAP_001.pdf

Adam, SDTM are structures of standards data from CDISC
- PHUSE ?  maintains examples of both.

define.xml (metadata, table, fields...)

------------------------ videos

** Videos 
2024 |  clinical submissions with r(ben):

- (@ 25:30) https://www.youtube.com/watch?v=5pf6mheqns4 ; merge, to from adsl
- (@ 36.01 ) template; sdtm -> adam (for adeg)
  [getting started][https://pharmaverse.github.io/admiral/articles/admiral.html]]
  check:  so idea is start with adsl structure, add necessary columns, rows

2023 | pharmaverse workshop (admiral, metatools, metacore  walkthrough - good, ross @ 7:00):
- (@7:00 or so) https://youtu.be/nHbDmxjVqRM?si=usfW_i9zdQyBKA0D

2022 | Day #1 (good) https://www.youtube.com/watch?v=9eod8MLF5ys
@ 23:12 - diagram, package handoffs...
@ 48:00  - Admiral, design flow of derive_var_... (good)

Coursera: https://www.coursera.org/learn/hands-on-clinical-reporting-using-r
New contributors https://www.youtube.com/watch?v=MhEyod3Sevc&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=3


------------------------ Reading


** Reading
   - (coding) https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
   - (*Programming Strategy*) https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html
   - (list ADAM variables & admiral function to create)https://pharmaverse.github.io/admiraldiscovery/articles/reactable.html
   - (examples: repo  ) https://github.com/pharmaverse/examples
   - (examples:  run in Posit Cloud) https://pharmaverse.github.io/examples/

*** Additional Reading (maybe older topics or presentations)
- (using tidyverse to maninpulate SDTM tibbles) https://www.pharmasug.org/proceedings/2023/QT/PharmaSUG-2023-QT-280.pdf
  

------------------------ packages

** R packages (Admiral, teal, ...)
   Begin here: https://pharmaverse.org/e2eclinical/
 
- **Admiral** overview:  Ben S https://www.youtube.com/watch?v=5PF6mHeQNS4
- functions create ADaM structures
- Intro (for Pharma Users):  https://pharmaverse.github.io/admiral/
- Getting Started (vignette, introducing code) https://pharmaverse.github.io/admiral/articles/admiral.html

 *Developers:*
- Contributing: https://pharmaverse.github.io/admiral/CONTRIBUTING.html
- Contribution Model:  broken link  
- FAQ (some background)https://pharmaverse.github.io/admiral/articles/faq.html


- *Admiraldev* (some background) https://pharmaverse.github.io/admiraldev/articles/admiraldev.html
Details:

- (2nd) Programming Strategy https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html
- (2nd) Coding (rlang etc)https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
- (2nd) PR overview https://pharmaverse.github.io/admiraldev/articles/pr_review_guidance.html
- (2nd) PR/branches/commits/ https://pharmaverse.github.io/admiraldev/articles/git_usage.html

- *datacutr* https://www.youtube.com/watch?v=ZyK-Tiqw5hU&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=6
  has sample data; functions to restrict data to ONE date, or patients ... a slice of data

- *metacore*  (Atorus, up to 6 datasets, info re:  tables, columns, ... )
SEE:  https://github.com/atorus-research/metacore
ds_spec  - dataset name, purupse (ex: AE, DM) info
ds_vars holds each field (columns) of dataset 
var_spec

...
File with reference datasets:ds ... https://github.com/atorus-research/metacore/blob/main/tests/testthat/test-reader.R
holds metadata specs as object; data may arrive in spreasheets or db for ... (company-specific)

- *metatools* https://github.com/pharmaverse/metatools

  tools to develop, work with metacore objects (ex:  companies may have different names to describe one entity)
  does some preliminary checks  (harder analysis is done in admiral)

- *oak*
  
- *random.cdisc.data* package:  create random AdAM datasets?
https://cran.r-project.org/web/packages/random.cdisc.data/random.cdisc.data.pdf

- *sdtmchecks*
  SEE:  https://www.youtube.com/watch?v=tBL0Eo6CBdw&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=5

- PharmaR:    *riskmetric* package  and a shiny app:  *Riskasessment*

- *TLG*  (tables, graphics ... ie display data)
https://pharmaverse.org/e2eclinical/tlg/



** tools
phuse.org/valtools (nice spreadsheet)


** US FDA
eCTR = electronic communications ..

SDTM =  Study Data Tabulation Model

TLF = Tables, Listings ..


*** ADSL  - required dataset format for CDISC (Adam); patient/treatment level ; 
attempt to capture treatments/interventions in a STUDY; must be flexible, yet rigourous.
(clear) https://www.linkedin.com/pulse/decoding-adsl-treatment-variables-study-designs-clinical-baghai-hhzfe/

*** LOCF https://www.lexjansen.com/nesug/nesug09/po/PO12.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4785044/
- missing observtions?    assume last reported value continues.


** SAS
Good validation (CDISC STDM/Admiral standard)

R has many packages, but who validates?






https://github.com/pharmaverse/ggsurvfit (seems interesting)

https://github.com/pharmaverse/envsetup (plumbing can be intersting)

https://github.com/insightsengineering/teal (70 issues, very active)

https://github.com/pharmaverse/pharmaverseadam/issues/58








** 



