---
output: html_document
editor_options: 
  chunk_output_type: console
---
folds: 
za
zo

# My Notes

## intro notes

(define-key evil-normal-state-map (kbd "<tab>") 'evil-toggle-fold)

S-<TAB> cycles
C-ENTER new line, at same level

## Tools

For Package:  Use these:

- styler::style_pkg() \
- devtools::lint()   # package   \
- devtools::test_coverage()   # entire package 
- devtools::spell_check(use_wordlist = TRUE) # package 
- spelling::update_wordlist(pkg=".") # runs spell AND asks to update WORDLIST  

For File:  Use these:

- active_fie =  rstudioapi::getSourceEditorContext()$path 
- devtools::test_active_file() 
- devtools::test_coverage_active_file()
- styler::style_file(path = )   # dir, file
- lintr::lint(filename="")
- spelling::update_wordlist(pkg=".") # runs spell and asks to update WORDLIST
- urlchecker::url_check()

(see lintr package - many options to control nolint)
https://lintr.r-lib.org/articles/lintr.html
lintr::lint()

```
# nolint start
...
# nolint end
 ```


## Videos & Reading

### Videos

2024 |  clinical submissions with r(ben):
- (@ 25:30) https://www.youtube.com/watch?v=5PF6mHeQNS4  to from adsl
- (@ 36.01 ) template; sdtm -> adam (for adeg)
  [getting started][https://pharmaverse.github.io/admiral/articles/admiral.html]]
  check:  so idea is start with adsl structure, add necessary columns, rows
  
  Review of Pilot 1 - 4 (25NOV2024)
  https://www.youtube.com/watch?v=4cqnIk9iDjs


2023 | pharmaverse workshop (admiral, metatools, metacore  walkthrough - good, ross @ 7:00):
- (@7:00 or so) https://youtu.be/nHbDmxjVqRM?si=usfW_i9zdQyBKA0D

2022 | CI/CD; pharmaverse github workflow (ben)
- https://www.youtube.com/watch?v=OcNzurpCCpY
- https://github.com/bms63/demo  
 

2022 | Day #1 (good) https://www.youtube.com/watch?v=9eod8MLF5ys
@ 23:12 - diagram, package handoffs...
@ 48:00  - Admiral, design flow of derive_var_... (good)

Coursera: https://www.coursera.org/learn/hands-on-clinical-reporting-using-r
New contributors https://www.youtube.com/watch?v=MhEyod3Sevc&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=3



### Reading

   - (overview) Ben, 2024 https://pharmasug.org/proceedings/2024/SD/PharmaSUG-2024-SD-343.pdf
 https://pharmasug.org/proceedings/2024/SS/PharmaSUG-2024-SS-344.pdf
   - (coding) https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
   - (*Programming Strategy*) https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html
   - (list ADAM variables & admiral function to create)https://pharmaverse.github.io/admiraldiscovery/articles/reactable.html
   - (examples: repo  ) https://github.com/pharmaverse/examples
   - (examples:  run in Posit Cloud) https://pharmaverse.github.io/examples/
   - Imputed Dates: (discussion) https://advance.hub.phuse.global/wiki/spaces/WEL/pages/26807243/Imputing+Partial+Dates

*** Additional Reading (maybe older topics or presentations)
- (using tidyverse to maninpulate SDTM tibbles) https://www.pharmasug.org/proceedings/2023/QT/PharmaSUG-2023-QT-280.pdf
  

## Buzz words

::: callout

Admiral 

:::

- **Admiral** overview:  Ben S https://www.youtube.com/watch?v=5PF6mHeQNS4
- functions create ADaM structures
- Intro (for Pharma Users):  https://pharmaverse.github.io/admiral/
- Getting Started (vignette, introducing code) https://pharmaverse.github.io/admiral/articles/admiral.html

 *for Developers:*
- Contributing: https://pharmaverse.github.io/admiral/CONTRIBUTING.html
- Contribution Model:  broken link  
- FAQ (some background)https://pharmaverse.github.io/admiral/articles/faq.html

**ADSL**  - required dataset format for CDISC (Adam); patient/treatment level ; 
attempt to capture treatments/interventions in a STUDY; must be flexible, yet rigourous.
(clear) https://www.linkedin.com/pulse/decoding-adsl-treatment-variables-study-designs-clinical-baghai-hhzfe/

- **Admiraldev** (some background) https://pharmaverse.github.io/admiraldev/articles/admiraldev.html

**box**

### All about CDISC 

#### The CDISC organization
CDISC (wikipedia) <https://en.wikipedia.org/wiki/Clinical_Data_Interchange_Standards_Consortium>
- Here focus on generic, abstract CDISC
- Avoid R implementions (add reference to implementations)

#### Why use CDISC specs?
To standardize structure of datasets that flow from patient to analysis.  So things like dates, units, dataset fields are consistent.The end user (gov't?) can easily work through great variety of clinical trials.

 Example:  In ADaM specify columns, or  the type (string, number etc)  is determined by metacore (metadata) and this in turn is based on ...


#### What exactly are these CDISC specs?
ODM
Define-XML



**CDISC Glossary:*  https://evs.nci.nih.gov/ftp1/CDISC/Glossary/CDISC%20Glossary.html
- CDISC data exchange definitions: https://www.cdisc.org/standards/data-exchange

**CDISC Genius** https://chatgpt.com/g/g-677223310d8081918ca4bdda574a5384-cdisc-genius 
**CDISC Video Primer:* (* start) https://www.cdisc.org/primer
**CDISC API LIBRARY** (info)  https://www.cdisc.org/cdisc-library

#### Examples: What is end result?
CDISC examples (JSON v xpt)
https://github.com/cdisc-org/DataExchange-DatasetJson/tree/master/examples
For anyone interested, **CDISC** has an open source **DataExchange repo** here with examples of the ADaM datasets {ADSL,ADAE,ADLBC,ADTTE,ADADAS} used in Pilot 5. Interesting to compare the  .xpt, .json, and .ndjson file formats and their properties. You can browse through using a Data Viewer. (Robert Devine)

### Define-XML
If metadata describes how to construct, CDISC objects, **Define-XML** describes how to encapsulate metadata, tabular dataset structure  into a JSON `container`.

**CDISC Define-XML** https://www.linkedin.com/groups/4975366/ This group is the official CDISC Define-XML page that will be used to discuss issues related to the development and implementation of the Define-XML standard as owned and developed by the CDISC Data Exchange Standards Team.

**CDISC Define-xml v 2.1** https://www.cdisc.org/standards/foundational/define-xml/define-xml-v2-1

#### What is Dataset-JSON ?
A JSON file 
**Dataset-JSON API specification**  trial, exammple candidate for spec <https://github.com/cdisc-org/DataExchange-DatasetJson-API>

https://github.com/cdisc-org/DataExchange-DatasetJson-API/blob/main/dataset-json-api.html

**CDISC Dataset-JSON v1.1 specification** https://github.com/cdisc-org/DataExchange-DatasetJson/blob/master/doc/dataset-json1-1.md 

- CDISC JSON v1.1.0 User's Guide <https://wiki.cdisc.org/display/PUB/Dataset-JSON+v1.1+User%27s+Guide> 
- (v 2.1) https://www.lexjansen.com/pharmasug/2022/DS/PharmaSUG-2022-DS-064.pdf

### R implemenation

**The *CDISC Analysis Results Data (ARD or ARDG) Model* is an emerging standard for encoding statistical analysis summaries in a machine-readable format. ( OCT 2024 https://www.danieldsjoberg.com/ARD-RinPharma-workshop-2024/ )


OpenClincal technical documentation:  <https://docs.openclinica.com/3-1-technical-documents/>

#### R implemenation
**datasetjson** Convert cdisc data between json and R data.frame + special attributes (good example code)  (json is usually only the transfer, not stored at either end).   **datasetjson** appears to hard code special attributes, ie not reading and incorporating info from JSON spec
https://github.com/atorus-research/datasetjson

datasetjson uses package jasonvalidate:: to confirm data and a schema match.

Blog: how JSON fits <https://swhume.github.io/why-json-for-datasets>

- Pinnacle 21 (was called openCDISC)
- video (Define.xml 2.0, pinnacle21) <https://www.youtube.com/watch?v=8PzYO0YlO0I>  Define.xml desribes content of an FDA submission.
- PharmaSUG 2022 Define-XML 2.0 to 2.1 <https://www.lexjansen.com/pharmasug/2022/DS/PharmaSUG-2022-DS-064.pdf>

- Pinnacle21 ( a company?) videos:<https://www.youtube.com/@pinnacle21llc/playlists>  
**json**
- (wikipedia)<https://en.wikipedia.org/wiki/JSON> 
- (syntax) <https://www.w3schools.com/js/js_json_syntax.asp> 
- (create a schema) <https://json-schema.org/learn/getting-started-step-by-step>
- (json for apis) <https://apisjson.org/>

- (* getting started, code) <https://atorus-research.github.io/datasetjson/articles/datasetjson.html>

- CDISC videos (https://www.youtube.com/@CDISCInc/playlists)
- SAS <https://www.youtube.com/playlist?list=PLbW_LFBIHlxu2abXtm0KE3HSZu1YCuRMO>
- FDA Pilot JSON <https://www.youtube.com/watch?v=ljr6d4Aw7nA> 



**define.xml** (metadata, table, fields...)

### after CDISC (placeholder)

- *datacutr* https://www.youtube.com/watch?v=ZyK-Tiqw5hU&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=6
  has sample data; functions to restrict data to ONE date, or patients ... a slice of data

- **expr() example**
call:  f(mtcars, var=expr(hp))  # no need to use "hp" (string)
f = function(ds, var) { dplyr::select(ds, !!var)}

**eCTD**
**eCTR** = electronic communications ..

**end-to-end clinical reporting** https://pharmaverse.org/e2eclinical/

**GxP** "Good Practice" esp regarding FDA submissions.

**LOCF** https://www.lexjansen.com/nesug/nesug09/po/PO12.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4785044/
- missing observtions?    assume last reported value continues.

- **metacore**  (Atorus, up to 6 datasets, info re:  tables, columns, ... )
creates R object to hold all metadata needed for an ADaM (structure of tables, columns etc)
Accepts .xslx, or define.xml, several formats that are company-specific.
This vignette explains the process, if given define.xml <https://github.com/atorus-research/metacore/blob/main/vignettes/Example.Rmd>

For .xml, reads using xml2 package, example: <https://xml2.r-lib.org/reference/read_xml.html#ref-examples>

video:  (10/20/2023, R/Pharma, Intro to Pharmaverse covers the process to ADaM)
<https://youtu.be/nHbDmxjVqRM?list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4>

Blog Post: <https://posit.co/blog/creating-adsl-with-the-pharmaverse-part-2/>

File with reference datasets:ds ... https://github.com/atorus-research/metacore/blob/main/tests/testthat/test-reader.R
SEE:  https://github.com/atorus-research/metacore

ds_spec  - dataset name, purupse (ex: AE, DM) info
ds_vars holds each field (columns) of dataset 
var_spec



- **metatools** https://github.com/pharmaverse/metatools
  tools to develop, work with metacore objects (ex:  companies may have different names to describe one entity)
  does some preliminary checks  (harder analysis is done in admiral)

**Pilot 3**
scripts, shiny -> generate ADaM (ADSL, ADAE) --> TLF

**Pilot 4**
container:  webassembly and Podman (not open source)
https://rpodcast.quarto.pub/pilot4-webassembly-adrg/#introduction  
https://github.com/RConsortium/submissions-pilot4-webR
- no .zip?  Docker?  .tar.gz?

**Pilot 5**

**Programming Strategy** https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html

Coding (rlang etc)https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
PR overview https://pharmaverse.github.io/admiraldev/articles/pr_review_guidance.html
PR/branches/commits/ https://pharmaverse.github.io/admiraldev/articles/git_usage.html

**PHUSE (UK)** - lots of conferences| https://phuse.global/Communications/Webinar_Wednesday https://phuse.global/Working_Groups [PHUSE Working Groups]
**pharmaR** (original attempt)  -> pharmaverse

**pinnacle21**  https://www.pinnacle21.com/
**oak**

**random.cdisc.data** package:  create random AdAM datasets?
https://cran.r-project.org/web/packages/random.cdisc.data/random.cdisc.data.pdf

**R Validation Hub** (~50 companies) |
**R Consortium Working Group** https://rconsortium.github.io/submissions-wg/ [R Consortium]  R Submissions Working Group] https://rconsortium.github.io/submissions-wg/

**R6** Advanced R Chapter 14

**rhino** good intro,box https://youtu.be/QmyilJr7jXs

**R Consortium Tables Working Group**:  https://rconsortium.github.io/rtrs-wg/

**riskmetric** package  and a shiny app:  *Riskasessment*

**SAP** - Statistical Analysis Plan |  Example: https://cdn.clinicaltrials.gov/large-docs/80/NCT04182880/SAP_001.pdf
What is SAP?
"A lot of what we make is based on the Study Design and questions
being asked in the study to prove the safety and efficacy of the drug
through something called the **SAP (Statistical Analysis Plan)**.  So
which ADaMs, TLFs you pick is really dependent on the SAP.  There is
something called the **Protocol** that is a higher-level version of the
SAP which influences the **eCRF (electronic Case Report Form)** and
determines what data is collected."  -- Ben Straub

**SAS**
Good validation (CDISC STDM/Admiral standard)
R has many packages, but who validates?


**SDTM** =  Study Data Tabulation Model https://en.wikipedia.org/wiki/SDTM

**sdtmchecks**
  SEE:  https://www.youtube.com/watch?v=tBL0Eo6CBdw&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=5

**TLG** -  tables, listings, graphics .... https://pharmaverse.org/e2eclinical/tlg/
- October 20, 2023 (rtables) https://www.youtube.com/watch?v=3S4_WROtFK8  j  k
- Pawel Rucki:  WebR to TLG, 25NOV2024  (Demo @15:48) https://youtu.be/vaoDUrUscZA?list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4

**Teal**
  Examples: Teal + ShinyLive (ie WebR; no need server) https://pharmaverse.github.io/examples/interactive/teal.html
  2024 Workshop:  https://github.com/pharmaverse/tealworkshop-phuseusconnect2024/tree/main/code
  Teal itself (Github) https://github.com/insightsengineering/teal (70 issues, very active)



**tools**
phuse.org/valtools (nice spreadsheet)


**Teal**
- May 16, 2023 Overview of Teal framework (no code) https://youtu.be/D2DJQYo3Nag
- October 20, 2023:(Dony| very good walk through of config modules,  filters, teal_slice(),  in basic teal app) https://www.youtube.com/watch?v=3S4_WROtFK8
- October 24, 2024 (Dony | intro to teal module) https://youtu.be/WnTgIWU59RM?list=PLbcglKxZP5PPrBVVV9AItiVXUCFcTQb9J 


https://github.com/pharmaverse/ggsurvfit (seems interesting)

https://github.com/pharmaverse/envsetup (plumbing can be intersting)


https://github.com/pharmaverse/pharmaverseadam/issues/58

**XLSX**  In Micrsoft Excel,   XLSX is an XML-based open file format and XLS is a proprietary Microsoft format.

## Empty Placeholder
## FAQ

**Tests**
In tests, how to check correct error/warning is issued?**

-  Please use expect_snapshot() to ensure that the correct error
message is issued.  By the way, unit test for errors and warnings
should never accept any error or warning but always check that the
expected one is issued (by using expect_snapshot() or the class
argument of expect_error()/expect_warning() ).

**Is my version of admiraldev, pharamverse, out-of-date?**
- Check:  Namespace file & packageVersion("admiraldev")
- install latest from github by using devtools::install_github("pharmaverse/admiraldev"

When we depend on a dev version of a package, we should also indicated this in our DESCRIPTION file FYI

Imports:
    admiraldev (>= 1.1.0.9006),

It used to be the case, that Remotes: would re-install all pkgs listed in Remotes upon installation of the pkg, but that is no longer the case after pak replaced remotes for GH intallations.


*Skills to focus on:*
https://pharmaverse.slack.com/archives/D07DL8CP00G/p1728234941977779
 `templates, documentation & navigation, pkgdown & organization, R environments`


*Data:*
https://pharmaverse.slack.com/archives/D07DL8CP00G/p1722857716071859

*What is "starting date" ?*
    When is example data contrived, from CDISC, a subset etc. the data usually starts at Informed Consent - RFISDTC

*When to use metacore/metatools ?   Or,   admiral?   Seems to be overlap.*

    Yes there are lots of overlap between the packages.  For example, there are functions in metatools to bring copies of variables from SDTM or you could just use dplyr or base R to bring them over.  We built them independent so you didn't have to commit to them if you wanted to use one or the other.  I use both in my ADaM programming and work well together.  I think the example site has best example.

*How many "ADaM(s)" are there?*

    3 types of Adam (ADSL, BDS, occ...)   Is there ONE ADSL or many kinds;  was very confused about this.

    There is only one ADSL in each study, but each study's ADSL will
    look different depending on what is needed for Subject-level data
    as defined in the Study SAP (Statistical Analysis Plan), for
    example baseline tables and endpoints.  There is a forth ADaM
    called ADaM Other - which captures some exotic ADaM structures.
   

**Templates:**
(not FAQ, a direction) We are trying to compare things from the templates in CI Workflow; use of diffdf

Why do we use both library(pharmaversesdtm::ae) and ae=pharamaversesdtm::ae

We are just trying to be explicit on where the data is coming from as
we are assuming folks are not super familiar with R yet if they are
using our template programs.  Yes we could drop the library() call,
but the comment on the datasets origin is important to also point out
to new users.


*What topics does bi-weekly Admiral meetings cover?*

A lot of what we make is based on the Study Design and questions being
asked in the study to prove the safety and efficacy of the drug
through something called the SAP (Statistical Analysis Plan).  So
which ADaMs, TLFs you pick is really dependent on the SAP.  There is
something called the Protocol that is a higher-level version of the
SAP which influences the eCRF (electronic Case Report Form) and
determines what data is collected.However, you will always have an
ADSL dataset!!

We have bi-weekly meetings on Wednesdays at 10 AM US EST.  They are
not mandatory to be in the group but highly encouraged.  You get to
meet various people and participate in discussions.  However, we
understand that can be tough with full-time job needs.  Occasionally
we split out into Working Groups to tackle various topics.

**History of package datasets**
https://app.slack.com/client/T028PB489D3/D07DL8CP00G

I'm not worried about creating the data in admiral.  I believe this is
the way forward that you have been working on.We have been doing it
for 3 years now just not using the recommended data/data-raw
convention.The pharmaverseadam package was created to allow folks to
load ADaM data for other projects rather than having to load admiral.
We actually used to have all those ADaMs in admiral but it bloated the
package and decided to remove them.  So pharamverseadam came later and
it is a little confusing as our templates make those ADaMs and so adsl
is identical between the two packages.The templates should create the
datasets (adsl and adlb).  admiral_adlb should require some subsetting
with the proposed Subjects.  If the data is not an exact match, then
it would be nice to understand what is not matching.  The diffdf
package is very nice for this.If it doesn't match, then lets figure
out why and it might just be a minor updates to the templates that
have been done over the last few years.  AGain I'm not particular
worried as the package hasn't changed so drastically that the Hy's
Vignette would become unusable. (edited)


*SAP* - Statistical Analysis Plan |  Example: https://cdn.clinicaltrials.gov/large-docs/80/NCT04182880/SAP_001.pdf


*How I join bi-weekly Admiral  meetings?*
https://github.com/pharmaverse/admiral/discussions/2169#discussioncomment-10376594

Once you do a few more successfully merged PRs I will propose to core
team that you be included! Be great to have you involved.

*Reviewers: PR*
(Ben) So I see everything that happens in admiral: issues, conversations,
PRs, etc as I have my settings that way.
Yes always assign a reviewer.
You can ping people you have interacted with and ask for review or use
@pharmaverse/admiral teams to ask for additional reviewers.
If crickets, ping on slack as well; Stefan is the best for thorough
code review.  Edoardo and I are okay for code, but we are very user
focused and pay close attention to documentation of usability of the
function.
there are a few others out there but you haven't interacted
with them much yet

**Steps before release**
   example of pre-release CRAN checklist  https://github.com/pharmaverse/admiral/discussions/2394 

## Working with JSON
See https://json-schema.org/learn/getting-started-step-by-step 

JSON data, but with more info not really sure of context, can even validate:  use JSON Schema!

```
{
  "productId": 1,
  "productName": "A green door",
  "price": 12.50,
  "tags": [ "home", "green" ]
}
```


Schema has few special `schema keywords`
With right tool, can validate the JSON data is indeed a valid JSON and follows JSON schema.
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Product",
  "description": "A product in the catalog",
  "type": "object",
  "properties" : {
	"productId": {
	  "description": "the productID is unique identifier",
	  "type": "integer"},
	"productName": {...},
	"price": {...},
	

   "required": [ "productId", "productName", "price" ]    # these are required
}
```


