#  ~/code/docs/tech_notes/_quarto.yml
# REF:  https://quarto.org/docs/reference/projects/options.html
# TODO:
#   - current date?
project:
  type: website  # default, website or book
  output-dir:  docs
# Render:  
#   - default:  all 
#   - can list specific files (only)
#   - can list do not render "!*.R"
#   - after using "!" , any additional files must be specifically listed
#  render:                             ## limit dir?  # default, render all files
   
  

website:
  title: "Meta + NSE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 410_bquote_example.qmd
        text: 410_bquote_example.qmd
      - href: about.qmd
        text: about.qmd
      - href: 250_quarto_cheat.qmd
        text: 250_quarto_cheat
      - href: 300_tech_notes.qmd
        text: 300_tech_notes.qmd

##  project-wide
format:
  html:
    theme: 
     -  cosmo
     -  custom.scss
    # css: styles.css
  
    toc: true
knitr:
  opts_chunk: 
    collapse: true
    comment: "..........>" 
execute:
  error: true
  cache: false
  output-dir: docs
  #  standalone: true 
  collapse: true

  


