project:
  type: website
  output-dir:  docs
  render:                             ## limit dir? 
#     - "018.2_abstract_syntax_tree.qmd"
#     - "410_bquote_example.qmd"
#     - "250_quarto_cheat.qmd"
#     - "300_tech_notes.qmd"
#     - "TEST.qmd"
    - "!*.R"          # do not render
    - "!*.Rmd"        # do not render 
   
  

website:
  title: "Meta + NSE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 410_bquote_example.qmd
        text: 410_bquote_example.qmd
      - href: about.qmd
        text: about.qmd
      - href: 250_quarto_cheat.qmd
        text: 250_quarto_cheat
      - href: 300_tech_notes.qmd
        text: 300_tech_notes.qmd
      - href: TEST.qmd

##  project-wide
format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
knitr:
  opts_chunk: 
    collapse: true
    comment: "..........>" 
execute:
  error: true
  cache: true
  output-dir: docs
  #  standalone: true 
  collapse: true

  


