
### Metaprogramming, NSE  

-   Hadley, Advanced R, version 1 (Expressions)
-   Quoting/Eval:  Lionel: https://rpubs.com/lionel-/programming-draft  
  -   https://rpubs.com/lionel-/tidyeval-introduction
  -   https://rpubs.com/lionel-/tidyeval-dplyr-recipes
  -   {{}} * https://www.tidyverse.org/blog/2019/06/rlang-0-4-0/
  -   https://rpubs.com/lionel-/superstache
    Brodie Gaslam
    -   https://www.brodieg.com/2020/05/05/on-nse/


### Articles

-   Quoting/Eval:  Lionel: https://rpubs.com/lionel-/programming-draft  
  -   https://rpubs.com/lionel-/tidyeval-introduction
  -   https://rpubs.com/lionel-/tidyeval-dplyr-recipes
  -   {{}} * https://www.tidyverse.org/blog/2019/06/rlang-0-4-0/
  -   https://rpubs.com/lionel-/superstache
    Brodie Gaslam
    -   https://www.brodieg.com/2020/05/05/on-nse/
-   https://www.rostrum.blog/2023/03/03/getparsedata/ (parse, tokens,  more advanced)
-   https://renkun.me/2020/11/08/using-parse-data-to-analyze-r-code/ (parse(), XPATH, rlanguage server)

-   function masking/pkgs: https://www.r-bloggers.com/2013/09/control-the-function-scope-by-the-r-package-namescope/ (using namespace to control scop)
-   {}} - https://www.r-bloggers.com/2019/06/curly-curly-the-successor-of-bang-bang-2/
-   env stack - https://www.r-bloggers.com/2014/12/tips-on-non-standard-evaluation-in-r/
-   quoting, dplyr - https://www.r-bloggers.com/2019/07/bang-bang-how-to-program-with-dplyr/
-   2012 namespace pkg, by Hadley, et al : https://cran.r-project.org/web/packages/namespace/index.html

-   **Examples**
  - http://zevross.com/blog/2018/09/11/writing-efficient-and-streamlined-r-code-with-help-from-the-new-rlang-package/ (mostly ggplot2)
  - Murdoch,  R Journal vol 2/2 2010
  - statisticsglob.com (several parse examples)
  - <https://statisticsglobe.com/parse-deparse-expression-r-function>
  - <advanced-r-solutions.rbind.io/expressions.html>
  - Tierney, codeTools ?

### Manuals:
  - R-exts:package-ns: https://cran.r-project.org/doc/manuals/R-exts.html#Package-namespaces
  - R-ints 
        -   1.2 https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Environments-and-variable-lookup
        -   1.4 C structs, Contexts  (https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Contexts)
        -   1.5 When is argument evaluated?
    R-Lang <https://cran.r-project.org/doc/manuals/R-lang.html>   
        -   2.1.3 Language Objects (calls, expressions, names)
        -   3   Evaluation
        -   6 Compute on Language: https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Computing-on-the-language
  - ns-load: https://stat.ethz.ch/R-manual/R-devel/library/base/html/ns-load.html
  - getFromNamespace: https://stat.ethz.ch/R-manual/R-devel/library/utils/html/getFromNamespace.html

-   **stackoverflow**

  - https://stackoverflow.com/questions/46834655/whats-the-difference-between-substitute-and-quote-in-r
  - https://stackoverflow.com/questions/14988722/in-r-what-does-loaded-via-a-namespace-and-not-attached-mean
  - {{}}https://stackoverflow.com/questions/62791997/what-is-the-embracing-operator
-   
-   **Posit**
  - ns, but not in package: https://community.rstudio.com/t/is-it-dangerous-to-create-a-namespace-for-functions-in-a-script-without-a-package/91141

### Packages using metaprogramming; environments
    -   wrapr https://winvector.github.io/wrapr/index.html useful?
    -   lintr  (parses)
    -   rlangserver
    -   envnames:: code for working with env, older https://github.com/mastropi/envnames
    -   

https://statisticsglobe.com/parse-deparse-expression-r-function
