
* My Notes

  

** Todo 
- tidyr, tlg?
- run @examples;  only when pkg is installed?
- templates, blocks of code?
  


** Questions
- Fake/synthetic data; many sources;  which one?
- Adam implementation guide?
  
  


** Terminology:  organizations & standards

- *PHUSE (UK)* - lots of conferences, relevance to coding? Wed webinar
[https://phuse.global/Communications/Webinar_Wednesday]
- *pharmaR* (original attempt)  -> pharmaverse
- *R Validation Hub* (~50 companies)
- [[R Submissions Working Group [https://rconsortium.github.io/submissions-wg/]]]
- pilot submissions to FDA

CDISC Glossary:  https://evs.nci.nih.gov/ftp1/CDISC/Glossary/CDISC%20Glossary.html
CDISC Video Primer: (how good?) https://www.cdisc.org/primer

Adam, SDTM are structures of standards data from CDISC
-Adam 
-SDTM - result of collecting organizing all the RAW DATA, spreadsheets and standardizing to this standard.
- PHUSE ?  maintains examples of both.

define.xml (metadata, table, fields...)


** REFE







** Videos 
2024 excellent videso:
- Clinical Submissions with R(Ben):

  #+BEGIN_VERSE
  Example:  Using admiral functions  to convert from SDTM (from pharmaversesdtm) to adsl (ADAM; sl=subject level)
  (@ 25:30) https://www.youtube.com/watch?v=5PF6mHeQNS4 //
  [Getting Started][https://pharmaverse.github.io/admiral/articles/admiral.html]] 
  (@ 36:01) 
  Template (admiral code, convert specific SDTM (ADEG to Adam version)
  #+END_VERSE

  #+BEGIN_VERSE
- 2023 Pharmaverse workshop (Admiral walkthrough - good, Ross @ 7:00):
  (@ 7:00) https://www.youtube.com/watch?v=nHbDmxjVqRM
- 2022
#+END_VERSE

#+BEGIN_VERSE
2022 
Day #1
https://www.youtube.com/watch?v=9eod8MLF5ys
@ 23:12 - diagram, package handoffs...
#+END_VERSE

Coursera: https://www.coursera.org/learn/hands-on-clinical-reporting-using-r
New contributors https://www.youtube.com/watch?v=MhEyod3Sevc&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=3


** Reading
   - (coding) https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
   - (programming strategy, ie naming) https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html


** R packages (Admiral, teal, ...)
   Begin here: https://pharmaverse.org/e2eclinical/
 
- **Admiral** overview:  Ben S https://www.youtube.com/watch?v=5PF6mHeQNS4
- functions create ADaM structures
- Intro (for Pharma Users):  https://pharmaverse.github.io/admiral/
- Getting Started (vignette, introducing code) https://pharmaverse.github.io/admiral/articles/admiral.html

 Developers:
- Contributing: https://pharmaverse.github.io/admiral/CONTRIBUTING.html
- Contribution Model:  broken link  
- FAQ (some background)https://pharmaverse.github.io/admiral/articles/faq.html


- *Admiraldev* (some background) https://pharmaverse.github.io/admiraldev/articles/admiraldev.html
Details:

- (2nd) Programming Strategy https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html
- (2nd) Coding (rlang etc)https://pharmaverse.github.io/admiral/articles/concepts_conventions.html
- (2nd) PR overview https://pharmaverse.github.io/admiraldev/articles/pr_review_guidance.html
- (2nd) PR/branches/commits/ https://pharmaverse.github.io/admiraldev/articles/git_usage.html

- *datacutr* https://www.youtube.com/watch?v=ZyK-Tiqw5hU&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=6
  has sample data; functions to restrict data to ONE date, or patients ... a slice of data

- *metacore*  (Atorus, up to 6 datasets, info re:  tables, columns, ... )
SEE:  https://github.com/atorus-research/metacore
ds_spec  - dataset name, purupse (ex: AE, DM) info
ds_vars holds each field (columns) of dataset 
var_spec

...
File with reference datasets:ds ... https://github.com/atorus-research/metacore/blob/main/tests/testthat/test-reader.R
holds metadata specs as object; data may arrive in spreasheets or db for ... (company-specific)

- *metatools* https://github.com/pharmaverse/metatools

  tools to develop, work with metacore objects (ex:  companies may have different names to describe one entity)
  does some preliminary checks  (harder analysis is done in admiral)

- *oak*
  
- *random.cdisc.data* package:  create random AdAM datasets?
https://cran.r-project.org/web/packages/random.cdisc.data/random.cdisc.data.pdf

- *sdtmchecks*
  SEE:  https://www.youtube.com/watch?v=tBL0Eo6CBdw&list=PLbcglKxZP5PPBplKMO9obNAjLIM7GGfp4&index=5

- PharmaR:    *riskmetric* package  and a shiny app:  *Riskasessment*

- *TLG*  (tables, graphics ... ie display data)
https://pharmaverse.org/e2eclinical/tlg/



** tools
phuse.org/valtools (nice spreadsheet)


** US FDA
eCTR = electronic communications ..

SDTM =  Study Data Tabulation Model

TLF = Tables, Listings ..


*** ADSL  - required dataset format for CDISC (Adam); patient/treatment level ; 
attempt to capture treatments/interventions in a STUDY; must be flexible, yet rigourous.
(clear) https://www.linkedin.com/pulse/decoding-adsl-treatment-variables-study-designs-clinical-baghai-hhzfe/

*** LOCF https://www.lexjansen.com/nesug/nesug09/po/PO12.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4785044/
- missing observtions?    assume last reported value continues.


** SAS
Good validation (CDISC STDM/Admiral standard)

R has many packages, but who validates?






https://github.com/pharmaverse/ggsurvfit (seems interesting)

https://github.com/pharmaverse/envsetup (plumbing can be intersting)

https://github.com/insightsengineering/teal (70 issues, very active)

https://github.com/pharmaverse/pharmaverseadam/issues/58








    




