---
title: "Untitled"
format: html
editor: source
output-dir:  docs
editor_options: 
  chunk_output_type: console
---

hellow
PURPOSE:		Misc Tech Notes;  details, notes can be here (but COMMANDS put
on INDEX C).  Math, R, probability and stats notes **do NOT go here*



\section{TODO:}
-   quarto STOPS

  -	See Index Cards (bottom) - integrate that point to very bottom into main text
	-	HTTR2 notes - mess
	-	Fix TOC
	-	In markdown (or latex), include separate files into this main one?
    -   Replace markdown headlines, with latex sections


\section{X11, Wayland, video}

Wayland is open source \textit{protocol} replacement for X windows, (widgets
says get graphics from X or Wayland).
WESTON is reference implementation.

Because Wayland accepts same toolkits (Qt, GTK) as X, the impact for developers
and users should be minimal.  Wayland shrinks X;  much functional now in Linux
kernel.  


\begin{verbatim}
\section{PDF, Pandoc, Latex}

 PDF   [ignores html, css; also ignores YAML header (pandoc & ::render()]

 To create pdf, just about everything works:  pandoc, markdown, latex, knitr..
 Note:  zathura uses library, open source `popler`.


  NOTE:   Missing latex .sty ?  
		-	With .tex file, run (in R) tinytex:latemk(*.tex) to install
		- OR, use tlmgr install <font>
		-	fonts installed?  fc-list : family
		- also luaotfload (loads fonts)
		-	ENGINE=software (such as **luatex**, tex, pdftex) 
		-	FORMAT=macros (such as **lualatex**)

  (Jan 2022) **Missing font, package?   TinyTex**
  *  update R
  *  keep_tex:  true (in YAML)
  *  at R console  tinytex::lualatex(".... .tex"), or tinytex::latexmk("*.tex")
  *  ~~ some times works, sometimes not ~~

  Lua in *.tex file
  *  see ~/code/publish_project/TEX/


!pandoc % -f markdown -o %.pdf

!pandoc % -f markdown  -t latex -H ../chapter_break.tex -V linkcolor:blue -V fontsize=11pt -V geometry:margin=0.3in -o ~/Downloads/print_and_delete/out.pdf
!pandoc % -f markdown  --pdf-engine lualatex -H chapter_break.tex -V linkcolor:blue -V fontsize=11pt -V geometry:margin=0.3in -o ~/Downloads/print_and_delete/out.pdf

!pandoc --metadata=project:JIM --lua-filter doc/panvimdoc/scripts/skip-blocks.lua --lua-filter doc/panvimdoc/scripts/include-files.lua  -t doc/panvimdoc/scripts/panvimdoc.lua % -o doc/source/jim_knitr_pandoc_latex.txt

-N					(Number sections)


  HTML [to produce HTML with pandoc, all latex is IGNORED.]  

I do **not** know how to create fancy HTML files from knitr, pandoc.

 HTML is pain in ass and HUGE time waste.  Pandoc can handle markdown and
 small amounts of latex (math) b/c ppl have added filters or other widgets to
 pandoc.

 If using Latex, its packages, diagrams with Latex ... must go with PDF.

-H header  
-V or --variable  
--pdf-engine=xelatex  



-	Try verbatum; process as a markdown.
pandoc balks at processing straight text if it thinks it sees markdown.
If lucky, !pandoc % -o file.pdf will work.

\end{verbatim}
