** Purpose
1. To obtain regular colonoscopy at Kaiser's Portland facitilites.
2. To regain regular access to appropriate Kaiser specialists (specifically
   urology, nephrology, GI and pancreas doctors), on a continual,
   ongoing basis when necessary and with minimal abscences.


** Background

*** Colonoscopy
My mother died of colon cancer at age 63.  Since my late 40s, I have
had regular colonoscopies every 3-5 years.   It has now been 7 years since the last procedure.

Not an expert, but having done this 5 or 6 times I am able to note how
different facilities operate, especially when complication. (I do not
empty on the usual time scale or prep, including 7 day liquid diets.
This is well-known, discussed with doctors both before and after.)

Each of the 5 or 6 times was done successfully.  Till the one done at
Peace Health in Eugene, OR (March 2024).

For purposes of this request
that procedure was a fisco leaving me with no colonscopy, ignored
phone calls, visit to ER and 2 weeks of diarehea:  a complete
abdication of responsibility.  Yet, the insurance company/CCO said it
paid the bill and considers the matter "private."  This puts others at risk.
It is astonding to
me that people responsible for health outcomes, safety and financial
see nothing wrong.

The upshot is the procedure, which still must be done, should be done
at Kaiser facilities where the doctors have already successfully
navigated this twice.



*** Specialist Access

I have been under Kaiser's care for kidney stones since 2014.
Following 2 URS procedures in 2 months, I have had small stones but no
major events (I appreciate!).  However, urine oxalate (UrOx) had
always been high, sometime extremely high.  Though a lot of effort, I
worked through a series of doctors (at Kaiser, OHSU, U Chicago, Mayo
Clinic).  Each step took months or even years.  The problem was traced
to fat malebsorption; large amount of fecat fat and pancraatic insufficiency. - but with NO other symptoms; due to pancreatic
insufficiency and large amount fecal fat.  Yet no other symptoms.
Enyzme replacements did nothing and were stopped.  But MRI revealed
presense of large number of cycsts.
Thus in  2024, the situation continues to be high UrOx, no symptoms due to high fecal fat.  But the large number of cysts in MRI 2024 raised questions by primary care, Dr. Mueller.   To his credit, he raised questions about the cysts and no enzymes and if a biospy might be useful.

He asked for "chart review" with appropriate specialists.   This was rejected.   It was the trigger for this.


Most baffling - and concerning.   A repeat MRI was ordered - not a biospy -  now scheduled for July 27, 2024.  In absense of other information, of course I will proceed.
When I called to make an appointment with GI doctor 
The doctor who authorized it;  is no out of office until 2057 I believe and I will be 102.

When I called, there was no GI appointsments and told to call back.  I do not know appointment this will also be rejected.












   
