

##  Notes for Dr. Miyake 2023-12-21 
### Hyperoxaluria / Fat Malabsoption/Pancreatic Atrophy (numerous cycts)  

**Review**  
  1.  August 2023 Litholink + recent Kaiser Labs  
  2.  Note:   Protein/Creatine ratio 1.01  
  3.  Dr. Lam (urology) defers several questions to you.  

**Potassium Citrate (now 4x daily, each 1080 mg Potassium) **  
**Calcium Citrate (now 4x daily, each 1333 mg Calcium)  **   
  4. Dr. Lam asks, reduce Potassium load?  
  - (Was set at 4 when 3 was insufficient, Dr. Wagner 2014-2015)  
  5.  My question:   pH was historically > 7 (diet?), is it the Citrate or the Potassium most needed?   
  6.  Can diet provide Citrate??   
   
**ZenPep**  
  7.  no perceived change or benefit, ceased mid-2022   
  8.  (Dr. Lieske:  "some" show no symptoms; 'some' do not respond to Enzymes)  

**Chronic High Urine Oxalate (50 - 80, but can exceed 130+)**  
  9. Given up on any kind of logical diet  
 10. Other than  literature, no doctor warnings that is harmful (other than stone risk). 


**ToDo:**
  - Litholink (early 2024).   Would you be willing over from Dr. Lam?  
  - KUB (early 2024)  
  - Next urine/blood labs?  
  - Next MRI (Pancreas) 2025, unless reason for sooner.  
  - Next colonoscopy - ASAP (7 years) 
```

\newpage

{{< pagebreak >}}

