---
title: "Car"
format: pdf 
editor_options: 
  chunk_output_type: console
editor: 
  markdown: 
    wrap: 72
---

------------------------ Itinerary

Oregon Rules:
https://www.oregon.gov/odot/dmv/pages/vehicle/titlereg.aspx Oregon Bill
of Sale: https://www.oregon.gov/odot/Forms/DMV/501fill.pdf

*Tuesday* - move funds to CASH account (done) - car *insurance* -
check - Nolo - *legal*, car title transfer/paymnet

-   convince Bob to pick up car himslef at his/Ingrid's convenience (I
    pay expenses)

-   Can be done ANY day convenient for both.

-   DRAFT agreement to Ingrid (see below)

-   Chuck - give key to Civic (in Eugene)

*Wednesday*

-   FINALIZE agreement with Ingrid

-   Ingrid signs, returns agreement

-   wire funds to Ingrid (today or Thursday, BEFORE 1 pm Pacific)

*Thursday*

-   What is NOT done?
-   *insurance* - change on day Bob's takes car.

*Friday* - train to PDX - checkin hotel (\> 2 pm ?) - prep 1st batch

*Saturday* - no activity *Sunday* - no activity

*Monday*

-   2pm ish, Bob picks me; EAT !
-   go to where car is: SLEEP

*Tuesday*

-   *LEAVE PDX* Whenever awake , alert
-   BEFORE 4 am
-   OR, wait 10-11 pm? I think highway driving NIGHT is safer! Calmer

\pagebreak

DRAFT

Payment and Ownership Transfer

References:

Vehicle Sale: https://www.oregon.gov/odot/Forms/DMV/501fill.pdf

Title and Register:
https://www.oregon.gov/odot/dmv/pages/vehicle/titlereg.aspx

(1) For physical transfer of vehicle (date/time TBD), please give to
    Bob: (Robert Gallup)

-   keys
-   signed, dated Vehicle Bill of Sale.
-   Title.

(2) However, for purposes of Wire Transfer, please

-   complete information required on Vehicle Bill of Sale, or
    equivalent.
-   please provide Bank account, Bank, name, address, etc
-   add:

Upon Bank's receipt of \$8000, I transfer all ownership and rights of
vehicle to Jim Rothstein. There are no liens or obligations on vehicle.
I have no further interest or financial interest in vehicle.

(3) "Physical title and vehicle transfer to done at mutually agreed
    time/day/location."o

11959 SW Canyon Rd Beaverton, OR 97005 United States

This is the location of a Home Goods store that is right next to the
Beaverton transit center. I will meet Bob there at 8:30am Friday.

(4) Please attach copy or photo of driver's license.
