
---
title: skeleton.qmd
date: last-modified
# Quarto requires title, if want date to appear
# ~/.config/kickstart/skeleton/skeleton.qmd
---
Outline

Opening:
    I have done a range of projects in different settings.   However, in  past
    several years I have focused on R and the related packages and uses.

    Like many, I could be very happy moving ahead to the new challenges in
    genoimcs, ML and modeling large amounts of data.   However, from my own
    experience I know a better immediate goal is solidify what I do know and
    fill in any gaps or weaknesses.  Improve the craft of  Improve the craft
    of R 

    So for example, I have worked both data.table and tidyverse but not
    comfortable saying where each breaks down and another tool might be more
    appropriate.  

Seek
    -	R coding position, primarily coding and related problem solving.


Possible roles:
    So I see myself as part of team that firms up what work has already been
    done.   For example, 

-   wrangle, workflows, pipelines
-   refactor code
-   improve function documentation
-   writing tests
-   work through know code issues
-   cooperatively develop project best practices, team tcoding style
   
Of course, I would like to maintain exposure to modeling process, EDA,
graphics.   But this can be done during down time, or my own time.

I bring:
    Stable coder; curious; 
    Willing to be informal mentor (or vice versa)
Don't want
    -	 not seeking team lead or other managing position.

Gap:
    You will notice a gap in my resume for the years I lived overseas in
    China.  A rich, broaden experience.   I did teach an introductory java
    course and then set up and managed a popular website for both Chinese and
    foreigners to exchange information in and around Dalian, China.

R: 
    Since then I have focused on the R package linux and related tools
    (neovim, github ...)

Ealier Projects:
    I did a number of database projects mostly with the Paradox database and
    some mySql.  These included a law firm conlflict database; large
    multi-table database for real estate (joint ventures and individual
    properties)


-	

vim:linebreak:nospell:nowrap:cul tw=78 fo=tqlnrc foldcolumn=1 cc=+1
