Jim Rothstein       
jimrothstein@gmail.com      
831-824-4304         
---
#title: skeleton.qmd
#date: last-modified
# Quarto requires title, if want date to appear
# ~/.config/kickstart/skeleton/skeleton.qmd
---

In different settings, I have done a range of database-related, SQL projects
in the private sector. However,  I now focus on R, its related packages and
wish to apply this to applications in the public sector.


Like many, I could be happy moving ahead to the new challenges in genomics, ML
and modeling large amounts of data.   However, my preferred intermediate goal
is to solidify what I do know and fill in gaps or weaknesses.  

This means writing better code and documentation; for example, better testing,
validating inputs,  catching exceptions. 

So I could immediately contribute to  a team environment, but in support
role, for example

-   wrangle data, or improve workflows, pipelines
-   refactor code
-   improve function documentation
-   write tests
-   work through known code issues
-   help document project best practices and coding style
   
Of course, I want to continue on to modeling process, EDA,
graphics.   But this can be done during down time, or my own time.

I also lived overseas in China, where I taught an introductory java course and
set up and managed a popular, multi-cultural website and forum for both
Chinese and foreigners Dalian, China.

I hope to be considered for a  role in your group and begin to contribute.

<!--
Earlier Projects:
    I did a number of database projects mostly with the Paradox database and
    some MySQL.  These included a law firm conflict database; large
    multi-table database for real estate (joint ventures and individual
    properties)
    
    -->


	
<!--
vim:linebreak:nospell:nowrap:cul tw=78 fo=tqlnrc foldcolumn=1 cc=+1
-->
