name: 100_emacs_notes.yaml

run-name:  run_name is render

on:
  workflow_dispatch:
    inputs:
      selected_filename:
        description: 'Enter the name of the file.' 
        required: true
        type: choice
        options: 
        - tech_notes/280_emacs_notes.qmd
        - tech_notes/300_tech_notes.qmd

permissions:
  contents:  write

jobs:
  quarto:
    runs-on: ubuntu-latest


    steps:
    - name: echo the selected_file
      run: |
        echo "You selected this file ${{ github.event.inputs.selected_filename }}"

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST

    - name:  install knitr
      run:  Rscript -e 'install.packages("knitr")'

    - name:  install rmarkdown
      run:  Rscript -e 'install.packages("rmarkdown")'

    - name: Render Quarto document
      run: |
        #quarto render README.Rmd	  --to gfm --output README.md
        quarto render ${{ github.event.inputs.selected_filename }}
	--to gfm --output 280_emacs_notes.md
        #quarto render 250_quarto_knitr_SCSS_NOTES.qmd --to gfm --output 250_quarto_knitr_SCSS_NOTES.md

    # Commit and push changes to README.md
    - name: Commit 280_emacs_notes.md
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add  ${{ github.events.inputs.selected_filename }}
        git commit -m "Update ${{ github.event.inputs.selected_filename }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

