name: 103_render_jobs.yaml

run-name:  103 HOLDING

## TODO:
## want render, all job files.qmd  to both pdf, md
on:
  workflow_dispatch:
    inputs:
      selected_filename:
        description: 'Enter the name of the file.'
        required: true
        type: choice
        options:
          - jobs/2025_feb_clinical_trials_resume.qmd

permissions:
  contents:  write

jobs:
  quarto:
    runs-on: ubuntu-latest


    steps:
    - name: echo the selected_file
      run: |
        echo "You selected this file ${{ github.event.inputs.selected_filename }}"

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST

    - name:  install knitr
      run:  Rscript -e 'install.packages("knitr")'

    - name:  install rmarkdown, et al
      run:  Rscript -e 'install.packages(c("rmarkdown", "rlang", "lubridate"))'

    - name: create output file name, then use in next chunk
      run:  echo '${{ github.event.inputs.selected.filename }}.md'

    - name: Render Quarto document
      run: |
        quarto render ${{ github.event.inputs.selected_filename }} \
          --to pdf --output ${{ github.event.inputs.selected.filename}}

#    - name: Render Quarto Project (Experiment)
#      uses: quarto-dev/quarto-actions/render@v2
#      with:
#        to: gfm
       path: jobs/*.qmd

#        git add  ${{ github.events.inputs.selected_filename }}
#        git commit -m "Update ${{ github.event.inputs.selected_filename }}" || \
#          echo "no changes; nothing to commit"

    - name: Commit 
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Ran quarto, save results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

